// Lookups over the generated beach index (scripts/beach/build.py). Safe to
// import from client components: titles, facets and links only.
import index from "./beach-index.json";
import type { AdvIndexEntry } from "./adventure-links";
import guideLinks from "./beach-guide-links.json";

export const beachIndex = index as AdvIndexEntry[];

const bySlug = new Map(beachIndex.map((e) => [e.slug, e]));

export function beachEntry(slug: string) {
  return bySlug.get(slug);
}

export function beachByKind(kind: AdvIndexEntry["kind"]) {
  return beachIndex.filter((e) => e.kind === kind);
}

/** Beach articles sharing a region or activity with this one, most overlap first. */
export function relatedBeach(slug: string, n = 6) {
  const me = bySlug.get(slug);
  if (!me) return [];
  const facets = new Set([...me.regions, ...me.activities]);
  return beachIndex
    .filter((e) => e.slug !== slug)
    .map((e) => ({ e, s: [...e.regions, ...e.activities].filter((f) => facets.has(f)).length + (e.kind === "pillar" ? 0.5 : 0) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, n)
    .map((x) => x.e);
}

// State package pages → beach articles about that state.
const byPackage: Record<string, string[]> = {
  goa: ["best-beaches-in-goa"],
  "andaman-nicobar": ["best-beaches-in-andaman"],
  lakshadweep: ["best-beaches-in-lakshadweep"],
  kerala: ["best-beaches-in-kerala"],
  karnataka: ["best-beaches-in-karnataka"],
  maharashtra: ["best-beaches-in-maharashtra"],
  "tamil-nadu": ["best-beaches-in-tamil-nadu"],
  odisha: ["best-beaches-in-odisha", "dolphin-watching-in-india"],
  gujarat: ["best-beaches-in-gujarat"],
  "andhra-pradesh": ["best-beaches-in-andhra-pradesh"],
  "west-bengal": ["best-beaches-in-west-bengal"],
  puducherry: ["best-beaches-in-puducherry"],
  "dadra-nagar-haveli-daman-diu": ["best-beaches-in-gujarat"],
};

export function beachForPackage(packageSlug: string) {
  return (byPackage[packageSlug] ?? []).map((s) => bySlug.get(s)).filter((e): e is AdvIndexEntry => Boolean(e));
}

// Guides that should point readers to a beach article (GuideTripCTA),
// generated by scripts/beach/build.py from scripts/beach/guide-links.json.
export const beachForGuide = guideLinks as Record<string, { slug: string; label: string }>;
