export const categories = [
  { id: "all", label: "All Posts" },
  { id: "destination-guides", label: "Destination Guides" },
  { id: "itineraries", label: "Itineraries" },
  { id: "adventure", label: "Adventure" },
  { id: "budget-travel", label: "Budget Travel" },
  { id: "trekking", label: "Trekking" },
  { id: "culture", label: "Culture" },
  { id: "tips", label: "Travel Tips" },
];

export const featuredPost = {
  slug: "leh-ladakh-road-trip",
  title: "Leh Ladakh Road Trip Guide: Routes, Permits, Passes & Tips",
  excerpt:
    "Moonscapes, Buddhist monasteries, and the world's highest motorable passes — the most complete Leh Ladakh road trip guide you'll find, written after 14 days on the ground.",
  image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
  category: "Road Trip",
  categoryColor: "bg-stone-100 text-stone-700",
  tags: ["Ladakh", "Road Trip", "High Altitude"],
  readTime: "26 min",
};

export const posts = [
  {
    slug: "odisha-travel-guide",
    title: "Odisha Travel Guide: Konark, Puri & Chilika Lake",
    excerpt:
      "A stone temple carved as a giant chariot, one of Hinduism's holiest shrines, and a lagoon where Irrawaddy dolphins surface between fishing boats — the complete guide to India's most underrated temple state.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Odisha", "Konark", "Puri"],
    readTime: "15 min",
    featured: true,
  },
  {
    slug: "punjab-travel-guide",
    title: "Punjab Travel Guide: Golden Temple, Amritsar & Wagah Border",
    excerpt:
      "A temple that shimmers gold over a sacred pool, a nightly border ceremony full of pageantry, and food that shaped how the rest of India eats — the complete guide to Punjab.",
    image: "/images/destinations/udaipur/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Punjab", "Amritsar", "Golden Temple"],
    readTime: "14 min",
    featured: true,
  },
  {
    slug: "rajasthan-travel-guide",
    title: "Rajasthan Travel Guide: Jaipur, Jodhpur & Pushkar Circuit",
    excerpt:
      "Pink-walled bazaars, a fort city painted entirely blue, and royal palaces still standing where maharajas built them centuries ago — the complete guide to Rajasthan's classic circuit.",
    image: "/images/destinations/jaisalmer/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Rajasthan", "Jaipur", "Jodhpur"],
    readTime: "19 min",
    featured: true,
  },
  {
    slug: "sikkim-travel-guide",
    title: "Sikkim Travel Guide: Gangtok, Yumthang Valley & Nathula Pass",
    excerpt:
      "Alpine lakes above 12,000 feet, a valley that turns into a carpet of rhododendrons every spring, and unobstructed views of Kanchenjunga — the complete guide to Sikkim.",
    image: "/images/destinations/manali/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sikkim", "Gangtok", "Yumthang Valley"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "tamil-nadu-travel-guide",
    title: "Tamil Nadu Travel Guide: Madurai, Mahabalipuram & Ooty",
    excerpt:
      "Temple towers carved with thousands of painted deities, UNESCO shore temples on the Bay of Bengal, and tea gardens in the Nilgiri hills — the complete guide to Dravidian India.",
    image: "/images/destinations/hampi/virupaksha.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Tamil Nadu", "Madurai", "Ooty"],
    readTime: "18 min",
    featured: true,
  },
  {
    slug: "tripura-travel-guide",
    title: "Tripura Travel Guide: Neermahal, Unakoti & Ujjayanta Palace",
    excerpt:
      "A palace rising from the middle of a lake, giant rock-cut carvings hidden in the forest, and a royal capital barely anyone's heard of — the complete guide to India's most overlooked princely state.",
    image: "/images/destinations/ziro/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Tripura", "Neermahal", "Unakoti"],
    readTime: "12 min",
    featured: true,
  },
  {
    slug: "nagaland-travel-guide",
    title: "Nagaland Travel Guide: Hornbill Festival, Kohima & Dzukou Valley",
    excerpt:
      "A festival where sixteen tribes gather in their warrior best, a war cemetery from a WWII turning point, and a valley called the Switzerland of the East — the complete guide to Nagaland.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Nagaland", "Hornbill Festival", "Kohima"],
    readTime: "15 min",
    featured: true,
  },
  {
    slug: "mizoram-travel-guide",
    title: "Mizoram Travel Guide: Aizawl, Reiek & Vantawng Falls",
    excerpt:
      "A hillside capital with no traffic jams, a waterfall dropping through pine-covered gorges, and one of India's cleanest, most literate states — the complete guide to Mizoram.",
    image: "/images/destinations/meghalaya/dawki-river.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Mizoram", "Aizawl", "Reiek"],
    readTime: "13 min",
    featured: true,
  },
  {
    slug: "manipur-travel-guide",
    title: "Manipur Travel Guide: Loktak Lake, Imphal & Kangla Fort",
    excerpt:
      "Floating islands drifting across a shimmering lake, the world's only floating national park, and a market run entirely by women for centuries — the complete guide to Manipur.",
    image: "/images/destinations/meghalaya/dawki-river.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Manipur", "Loktak Lake", "Imphal"],
    readTime: "14 min",
    featured: true,
  },
  {
    slug: "maharashtra-travel-guide",
    title: "Maharashtra Travel Guide: Mumbai, Ajanta-Ellora & Konkan Coast",
    excerpt:
      "A city that never sleeps, 2,000-year-old rock-cut cave temples, and a coastline dotted with sea forts and fishing villages — the complete guide to Maharashtra.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Maharashtra", "Mumbai", "Ajanta-Ellora"],
    readTime: "17 min",
    featured: true,
  },
  {
    slug: "madhya-pradesh-travel-guide",
    title: "Madhya Pradesh Travel Guide: Khajuraho, Bandhavgarh & Gwalior Fort",
    excerpt:
      "Temples carved with astonishing detail, some of India's best tiger sightings, and a hilltop fortress that guarded the heart of the country — the complete guide to Madhya Pradesh.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Madhya Pradesh", "Khajuraho", "Bandhavgarh"],
    readTime: "17 min",
    featured: true,
  },
  {
    slug: "uttar-pradesh-travel-guide",
    title: "Uttar Pradesh Travel Guide: Taj Mahal, Varanasi & Lucknow",
    excerpt:
      "The world's most famous monument to love, the ghats of Varanasi, and Lucknow's Nawabi elegance — the complete guide to India's most historically dense state.",
    image: "/images/destinations/udaipur/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Uttar Pradesh", "Taj Mahal", "Varanasi"],
    readTime: "17 min",
    featured: true,
  },
  {
    slug: "uttarakhand-travel-guide",
    title: "Uttarakhand Travel Guide: Char Dham, Nainital & Rishikesh",
    excerpt:
      "Sacred temples above 3,000 metres, the Ganga's first rush out of the mountains, and lake towns wrapped in pine forest — the complete guide to Dev Bhoomi.",
    image: "/images/destinations/rishikesh/rishikesh.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Uttarakhand", "Char Dham", "Rishikesh"],
    readTime: "19 min",
    featured: true,
  },
  {
    slug: "west-bengal-travel-guide",
    title: "West Bengal Travel Guide: Kolkata, Darjeeling & Sundarbans",
    excerpt:
      "Colonial-era Kolkata, tea gardens climbing into the clouds at Darjeeling, and mangrove creeks where the Royal Bengal Tiger still roams — the complete guide.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["West Bengal", "Kolkata", "Darjeeling"],
    readTime: "18 min",
    featured: true,
  },
  {
    slug: "delhi-travel-guide",
    title: "Delhi Travel Guide: Red Fort, Qutub Minar & 3-Day Itinerary",
    excerpt:
      "Mughal forts, Sultanate-era minarets, colonial avenues, and one of the world's great street food scenes — the complete guide to India's layered capital.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Delhi", "Red Fort", "Street Food"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "chandigarh-travel-guide",
    title: "Chandigarh Travel Guide: Rock Garden, Sukhna Lake & Itinerary",
    excerpt:
      "Le Corbusier's modernist Capitol Complex, a rock garden built entirely from industrial waste, and a lake at the foot of the Shivaliks — the complete guide to India's most planned city.",
    image: "/images/destinations/rishikesh/rishikesh.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Chandigarh", "Rock Garden", "Sukhna Lake"],
    readTime: "11 min",
    featured: true,
  },
  {
    slug: "dadra-nagar-haveli-daman-diu-guide",
    title: "Dadra & Nagar Haveli and Daman & Diu Travel Guide",
    excerpt:
      "A 16th-century Portuguese sea fort, near-empty beaches, and duty-free shopping — the complete guide to India's smallest, most overlooked Union Territory.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Diu", "Daman", "Silvassa"],
    readTime: "13 min",
    featured: true,
  },
  {
    slug: "jammu-kashmir-travel-guide",
    title: "Jammu & Kashmir Travel Guide: Srinagar, Gulmarg & Pahalgam",
    excerpt:
      "Houseboats on Dal Lake, gondola rides above the snow line, and valleys that earned Kashmir the name 'Paradise on Earth' — the complete guide.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Jammu & Kashmir", "Srinagar", "Gulmarg"],
    readTime: "15 min",
    featured: true,
  },
  {
    slug: "lakshadweep-island-guide",
    title: "Lakshadweep Travel Guide: Permits, Islands & Best Time to Visit",
    excerpt:
      "Coral atolls barely a kilometre wide, turquoise lagoons, and some of India's clearest diving water — the complete guide to India's least-visited tropical paradise.",
    image: "/images/destinations/lakshadweep/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Lakshadweep", "Coral Islands", "Scuba Diving"],
    readTime: "12 min",
    featured: true,
  },
  {
    slug: "puducherry-french-quarter-guide",
    title: "Puducherry Travel Guide: French Quarter, Auroville & Beaches",
    excerpt:
      "Mustard-yellow colonial villas, a seafront promenade closed to traffic, and the golden Matrimandir at Auroville — the complete guide to India's most European town.",
    image: "/images/destinations/puducherry/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Puducherry", "Tamil Nadu", "French Quarter"],
    readTime: "10 min",
    featured: true,
  },
  {
    slug: "ziro-valley-arunachal",
    title: "Ziro Valley Travel Guide: Apatani Villages, Rice Fields & Festival",
    excerpt:
      "A UNESCO tentative heritage site in Arunachal — home to the Apatani tribe, terraced rice fields and one of India's best music festivals.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Ziro Valley", "Arunachal Pradesh", "Off-beat"],
    readTime: "11 min",
    featured: true,
  },
  {
    slug: "gokarna-beaches",
    title: "Gokarna Travel Guide: Best Beaches, Temples & Itinerary",
    excerpt:
      "A temple town with world-class beaches — Om Beach, Half Moon, and Paradise — linked by a cliffside trek and still a fraction as commercial as Goa.",
    image: "/images/destinations/coorg/coorg.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Gokarna", "Karnataka", "Beaches"],
    readTime: "9 min",
    featured: true,
  },
  {
    slug: "goa-beaches-guide",
    title: "Goa Travel Guide: Best Beaches, North vs South & Itinerary",
    excerpt:
      "Portuguese-era churches, beach shacks, and a coastline that switches from party-loud to monastery-quiet within a few kilometres — the complete guide to Goa.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Goa", "Beaches"],
    readTime: "12 min",
    featured: true,
  },
  {
    slug: "udaipur-city-of-lakes",
    title: "Udaipur Travel Guide: City Palace, Lake Pichola & Itinerary",
    excerpt:
      "Palaces that appear to float on still water, whitewashed havelis and the most romantic skyline in Rajasthan — the complete guide to the City of Lakes.",
    image: "/images/destinations/jaisalmer/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Udaipur", "Rajasthan"],
    readTime: "10 min",
    featured: true,
  },
  {
    slug: "meghalaya-travel-guide",
    title: "Meghalaya Travel Guide: Living Root Bridges, Cherrapunji & More",
    excerpt:
      "Double-decker living root bridges, the cleanest river in Asia, and waterfalls that drop straight out of the clouds — the complete guide to India's wettest state.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Meghalaya", "Northeast India"],
    readTime: "20 min",
    featured: true,
  },
  {
    slug: "manali-travel-guide",
    title: "Manali Travel Guide: Top Places, Itinerary & Insider Tips",
    excerpt:
      "The definitive guide to Manali — Rohtang Pass, Solang Valley, Old Manali cafes, and a 5-day itinerary that covers it all.",
    image: "/images/destinations/manali/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Manali", "Himachal Pradesh"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "spiti-valley-travel-guide",
    title: "Spiti Valley: The Complete Travel Guide",
    excerpt:
      "A cold desert between Tibet and India — monasteries, fossils, and roads that will test your nerve and reward your soul.",
    image: "/images/destinations/spiti-valley/spiti-valley.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Spiti Valley", "Off-beat"],
    readTime: "22 min",
    featured: true,
  },
  {
    slug: "rishikesh-adventure-guide",
    title: "Rishikesh Travel Guide: Adventure, Yoga, Rafting & More",
    excerpt:
      "India's adventure capital where white-water rafting meets Ganga aarti — everything you need for the perfect Rishikesh trip.",
    image: "/images/destinations/rishikesh/rishikesh.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Rishikesh", "Rafting", "Yoga"],
    readTime: "18 min",
    featured: true,
  },
  {
    slug: "coorg-guide",
    title: "Coorg Travel Guide: Coffee, Waterfalls, Trekking & More",
    excerpt:
      "Misty coffee hills, thundering waterfalls, Nagarhole wildlife and Kodava warmth — South India's most quietly magnificent escape.",
    image: "/images/destinations/coorg/coorg.jpg",
    category: "Destination Guide",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Coorg", "Karnataka", "Coffee"],
    readTime: "17 min",
    featured: false,
  },
  {
    slug: "leh-ladakh-road-trip",
    title: "Leh Ladakh Road Trip Guide",
    excerpt:
      "Pangong Tso, Nubra Valley, Khardung La and 14 days on the most dramatic roads on earth.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Road Trip",
    categoryColor: "bg-stone-100 text-stone-700",
    tags: ["Ladakh", "Road Trip"],
    readTime: "26 min",
    featured: false,
  },
  {
    slug: "kasol-kheerganga-trek",
    title: "Kasol & Kheerganga: The Backpacker's Himalayan Trail",
    excerpt:
      "Follow the Parvati River to natural hot springs through pine forests and tiny Himalayan villages.",
    image: "/images/destinations/kasol/kasol.jpg",
    category: "Trekking",
    categoryColor: "bg-green-100 text-green-700",
    tags: ["Kasol", "Trekking"],
    readTime: "12 min",
    featured: false,
  },
];

export const popularTags = [
  "Himachal Pradesh",
  "Ladakh",
  "Uttarakhand",
  "Karnataka",
  "Road Trip",
  "Trekking",
  "Budget Travel",
  "Solo Travel",
  "Adventure",
  "Yoga",
  "Wildlife",
  "Beaches",
  "Heritage",
  "Off-beat",
];

export const readingListItems = [
  {
    slug: "manali-travel-guide",
    title: "Manali Travel Guide",
    readTime: "16 min",
  },
  {
    slug: "spiti-valley-travel-guide",
    title: "Spiti Valley Complete Guide",
    readTime: "22 min",
  },
  {
    slug: "rishikesh-adventure-guide",
    title: "Rishikesh Adventure Guide",
    readTime: "18 min",
  },
  { slug: "coorg-guide", title: "Coorg Travel Guide", readTime: "17 min" },
];
