// `id` matches the `category` value used on each post in `posts` below,
// so filtering is a direct equality check with no separate mapping table.
export const categories = [
  { id: "all", label: "All Guides" },
  { id: "Destination Guide", label: "Destination Guides" },
  { id: "Off-beat", label: "Off-beat" },
  { id: "Heritage", label: "Heritage" },
  { id: "Beaches", label: "Beaches" },
  { id: "Trekking", label: "Trekking" },
  { id: "Road Trip", label: "Road Trip" },
  { id: "Adventure", label: "Adventure" },
];

export const featuredPost = {
  slug: "leh-ladakh-road-trip-travel-guide",
  title: "Leh Ladakh Road Trip Guide: Routes, Permits, Passes & Tips",
  excerpt:
    "Moonscapes, Buddhist monasteries, and the world's highest motorable passes — the most complete Leh Ladakh road trip guide you'll find, written after 14 days on the ground.",
  image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
  category: "Road Trip",
  categoryColor: "bg-stone-100 text-stone-700",
  tags: ["Ladakh", "Road Trip", "High Altitude"],
  readTime: "26 min",
};

export const posts = [
  {
    slug: "odisha-travel-guide",
    title: "Odisha Travel Guide: Konark, Puri & Chilika Lake",
    excerpt:
      "A stone temple carved as a giant chariot, one of Hinduism's holiest shrines, and a lagoon where Irrawaddy dolphins surface between fishing boats — the complete guide to India's most underrated temple state.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Odisha", "Konark", "Puri"],
    readTime: "15 min",
    featured: true,
  },
  {
    slug: "punjab-travel-guide",
    title: "Punjab Travel Guide: Golden Temple, Amritsar & Wagah Border",
    excerpt:
      "A temple that shimmers gold over a sacred pool, a nightly border ceremony full of pageantry, and food that shaped how the rest of India eats — the complete guide to Punjab.",
    image: "/images/destinations/udaipur/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Punjab", "Amritsar", "Golden Temple"],
    readTime: "14 min",
    featured: true,
  },
  {
    slug: "rajasthan-travel-guide",
    title: "Rajasthan Travel Guide: Jaipur, Jodhpur & Pushkar Circuit",
    excerpt:
      "Pink-walled bazaars, a fort city painted entirely blue, and royal palaces still standing where maharajas built them centuries ago — the complete guide to Rajasthan's classic circuit.",
    image: "/images/destinations/jaisalmer/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Rajasthan", "Jaipur", "Jodhpur"],
    readTime: "19 min",
    featured: true,
  },
  {
    slug: "sikkim-travel-guide",
    title: "Sikkim Travel Guide: Gangtok, Yumthang Valley & Nathula Pass",
    excerpt:
      "Alpine lakes above 12,000 feet, a valley that turns into a carpet of rhododendrons every spring, and unobstructed views of Kanchenjunga — the complete guide to Sikkim.",
    image: "/images/destinations/manali/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sikkim", "Gangtok", "Yumthang Valley"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "tamil-nadu-travel-guide",
    title: "Tamil Nadu Travel Guide: Madurai, Mahabalipuram & Ooty",
    excerpt:
      "Temple towers carved with thousands of painted deities, UNESCO shore temples on the Bay of Bengal, and tea gardens in the Nilgiri hills — the complete guide to Dravidian India.",
    image: "/images/destinations/hampi/virupaksha.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Tamil Nadu", "Madurai", "Ooty"],
    readTime: "18 min",
    featured: true,
  },
  {
    slug: "tripura-travel-guide",
    title: "Tripura Travel Guide: Neermahal, Unakoti & Ujjayanta Palace",
    excerpt:
      "A palace rising from the middle of a lake, giant rock-cut carvings hidden in the forest, and a royal capital barely anyone's heard of — the complete guide to India's most overlooked princely state.",
    image: "/images/destinations/ziro/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Tripura", "Neermahal", "Unakoti"],
    readTime: "12 min",
    featured: true,
  },
  {
    slug: "nagaland-travel-guide",
    title: "Nagaland Travel Guide: Hornbill Festival, Kohima & Dzukou Valley",
    excerpt:
      "A festival where sixteen tribes gather in their warrior best, a war cemetery from a WWII turning point, and a valley called the Switzerland of the East — the complete guide to Nagaland.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Nagaland", "Hornbill Festival", "Kohima"],
    readTime: "15 min",
    featured: true,
  },
  {
    slug: "mizoram-travel-guide",
    title: "Mizoram Travel Guide: Aizawl, Reiek & Vantawng Falls",
    excerpt:
      "A hillside capital with no traffic jams, a waterfall dropping through pine-covered gorges, and one of India's cleanest, most literate states — the complete guide to Mizoram.",
    image: "/images/destinations/meghalaya/dawki-river.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Mizoram", "Aizawl", "Reiek"],
    readTime: "13 min",
    featured: true,
  },
  {
    slug: "manipur-travel-guide",
    title: "Manipur Travel Guide: Loktak Lake, Imphal & Kangla Fort",
    excerpt:
      "Floating islands drifting across a shimmering lake, the world's only floating national park, and a market run entirely by women for centuries — the complete guide to Manipur.",
    image: "/images/destinations/meghalaya/dawki-river.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Manipur", "Loktak Lake", "Imphal"],
    readTime: "14 min",
    featured: true,
  },
  {
    slug: "maharashtra-travel-guide",
    title: "Maharashtra Travel Guide: Mumbai, Ajanta-Ellora & Konkan Coast",
    excerpt:
      "A city that never sleeps, 2,000-year-old rock-cut cave temples, and a coastline dotted with sea forts and fishing villages — the complete guide to Maharashtra.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Maharashtra", "Mumbai", "Ajanta-Ellora"],
    readTime: "17 min",
    featured: true,
  },
  {
    slug: "madhya-pradesh-travel-guide",
    title: "Madhya Pradesh Travel Guide: Khajuraho, Bandhavgarh & Gwalior Fort",
    excerpt:
      "Temples carved with astonishing detail, some of India's best tiger sightings, and a hilltop fortress that guarded the heart of the country — the complete guide to Madhya Pradesh.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Madhya Pradesh", "Khajuraho", "Bandhavgarh"],
    readTime: "17 min",
    featured: true,
  },
  {
    slug: "gujarat-travel-guide",
    title: "Gujarat Travel Guide: Rann of Kutch, Somnath & Gir National Park",
    excerpt:
      "A shimmering white salt desert stretching to the horizon, temple towns steeped in mythology, and the last wild lions outside Africa — Gujarat is India's most quietly extraordinary state.",
    image: "/images/destinations/jaisalmer/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Gujarat", "Rann of Kutch", "Gir National Park"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "haryana-travel-guide",
    title: "Haryana Travel Guide: Kurukshetra, Surajkund & Panchkula",
    excerpt:
      "The ground where the Bhagavad Gita is said to have been spoken, one of the world's largest craft fairs, and the easiest weekend escape from Delhi-NCR — Haryana doesn't oversell itself, and that's exactly the point.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Haryana", "Kurukshetra", "Surajkund"],
    readTime: "11 min",
    featured: true,
  },
  {
    slug: "himachal-pradesh-travel-guide",
    title: "Himachal Pradesh Travel Guide: Shimla, Manali & Dharamshala",
    excerpt:
      "From colonial Shimla's toy train to the Tibetan Buddhist calm of McLeod Ganj and the apple orchards of Kullu — a state-level guide to planning a multi-region Himachal Pradesh trip.",
    image: "/images/destinations/manali/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Himachal Pradesh", "Shimla", "Dharamshala"],
    readTime: "20 min",
    featured: true,
  },
  {
    slug: "jharkhand-travel-guide",
    title: "Jharkhand Travel Guide: Netarhat, Betla National Park & Waterfalls",
    excerpt:
      "Dense sal forests, waterfalls that thunder off laterite cliffs, and tiger territory at Betla — Jharkhand is one of India's most underrated, off-the-beaten-path states.",
    image: "/images/destinations/ziro/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Jharkhand", "Netarhat", "Betla National Park"],
    readTime: "13 min",
    featured: true,
  },
  {
    slug: "karnataka-travel-guide",
    title: "Karnataka Travel Guide: Bangalore, Mysore & Hampi",
    excerpt:
      "From Bangalore's tech-city energy to Mysore's royal palaces, the ancient ruins of Hampi, and coffee hills beyond — a complete guide to planning a multi-region trip across Karnataka.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Karnataka", "Bangalore", "Mysore"],
    readTime: "19 min",
    featured: true,
  },
  {
    slug: "andhra-pradesh-travel-guide",
    title: "Andhra Pradesh Travel Guide: Tirupati, Visakhapatnam & Araku Valley",
    excerpt:
      "From the world's richest temple at Tirumala to Vizag's underrated coastline and the coffee-scented hills of Araku Valley — a complete guide to Andhra Pradesh's pilgrimage sites, beaches, and fiery cuisine.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Andhra Pradesh", "Tirupati", "Visakhapatnam"],
    readTime: "17 min",
    featured: true,
  },
  {
    slug: "arunachal-pradesh-travel-guide",
    title: "Arunachal Pradesh Travel Guide: Tawang, Ziro Valley & Bomdila",
    excerpt:
      "From Tawang's Himalayan monasteries to Ziro's terraced tribal valleys, this is the complete guide to India's largest and least-visited Northeastern state — permits, passes, and all.",
    image: "/images/destinations/ziro/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Arunachal Pradesh", "Tawang", "Ziro Valley"],
    readTime: "19 min",
    featured: true,
  },
  {
    slug: "assam-travel-guide",
    title: "Assam Travel Guide: Kaziranga, Guwahati & Majuli Island",
    excerpt:
      "Rhino safaris in Kaziranga, a hilltop Shakti Peeth temple above the Brahmaputra, and the world's largest river island — Assam is the gateway to Northeast India and a destination worth its own trip.",
    image: "/images/destinations/meghalaya/dawki-river.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Assam", "Kaziranga", "Majuli Island"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "bihar-travel-guide",
    title: "Bihar Travel Guide: Bodh Gaya, Nalanda & Patna",
    excerpt:
      "The place where Buddha attained enlightenment, the ruins of one of the world's oldest universities, and the ancient heartland of the Magadha empire — a complete guide to Bihar's temples, ruins, and history for travelers.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Bihar", "Bodh Gaya", "Nalanda"],
    readTime: "15 min",
    featured: true,
  },
  {
    slug: "chhattisgarh-travel-guide",
    title: "Chhattisgarh Travel Guide: Chitrakote Falls, Bastar & Raipur",
    excerpt:
      "A horseshoe waterfall wider than Niagara, a tribal heartland with a 75-day festival tradition, and near-empty forest trails — Chhattisgarh is Central India's most overlooked state.",
    image: "/images/destinations/meghalaya/dawki-river.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Chhattisgarh", "Chitrakote Falls", "Bastar"],
    readTime: "13 min",
    featured: true,
  },
  {
    slug: "uttar-pradesh-travel-guide",
    title: "Uttar Pradesh Travel Guide: Taj Mahal, Varanasi & Lucknow",
    excerpt:
      "The world's most famous monument to love, the ghats of Varanasi, and Lucknow's Nawabi elegance — the complete guide to India's most historically dense state.",
    image: "/images/destinations/udaipur/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Uttar Pradesh", "Taj Mahal", "Varanasi"],
    readTime: "17 min",
    featured: true,
  },
  {
    slug: "uttarakhand-travel-guide",
    title: "Uttarakhand Travel Guide: Char Dham, Nainital & Rishikesh",
    excerpt:
      "Sacred temples above 3,000 metres, the Ganga's first rush out of the mountains, and lake towns wrapped in pine forest — the complete guide to Dev Bhoomi.",
    image: "/images/destinations/rishikesh/rishikesh.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Uttarakhand", "Char Dham", "Rishikesh"],
    readTime: "19 min",
    featured: true,
  },
  {
    slug: "west-bengal-travel-guide",
    title: "West Bengal Travel Guide: Kolkata, Darjeeling & Sundarbans",
    excerpt:
      "Colonial-era Kolkata, tea gardens climbing into the clouds at Darjeeling, and mangrove creeks where the Royal Bengal Tiger still roams — the complete guide.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["West Bengal", "Kolkata", "Darjeeling"],
    readTime: "18 min",
    featured: true,
  },
  {
    slug: "delhi-travel-guide",
    title: "Delhi Travel Guide: Red Fort, Qutub Minar & 3-Day Itinerary",
    excerpt:
      "Mughal forts, Sultanate-era minarets, colonial avenues, and one of the world's great street food scenes — the complete guide to India's layered capital.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Delhi", "Red Fort", "Street Food"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "chandigarh-travel-guide",
    title: "Chandigarh Travel Guide: Rock Garden, Sukhna Lake & Itinerary",
    excerpt:
      "Le Corbusier's modernist Capitol Complex, a rock garden built entirely from industrial waste, and a lake at the foot of the Shivaliks — the complete guide to India's most planned city.",
    image: "/images/destinations/rishikesh/rishikesh.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Chandigarh", "Rock Garden", "Sukhna Lake"],
    readTime: "11 min",
    featured: true,
  },
  {
    slug: "rock-garden-chandigarh-travel-guide",
    title: "Rock Garden Chandigarh: Nek Chand's Sculpture Garden Guide",
    excerpt:
      "Thousands of mosaic sculptures built secretly from industrial waste and broken bangles — Nek Chand's Rock Garden is Chandigarh's strangest, most beloved attraction.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Rock Garden", "Chandigarh", "Nek Chand", "Sector 1"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "sukhna-lake-chandigarh-travel-guide",
    title: "Sukhna Lake Chandigarh: Promenade, Boating & Best Time",
    excerpt:
      "A man-made lake at the foot of the Shivalik hills, ringed by a 3-km promenade — Sukhna Lake is Chandigarh's favourite sunrise and sunset spot.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sukhna Lake", "Chandigarh", "Sector 1", "Shivalik Hills"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "rose-garden-chandigarh-travel-guide",
    title: "Zakir Hussain Rose Garden: Chandigarh's Rose Festival Guide",
    excerpt:
      "Asia's largest rose garden — 30 acres and over 1,600 rose varieties in full bloom every February, right in the heart of Sector 16.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Rose Garden", "Chandigarh", "Sector 16", "Rose Festival"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "capitol-complex-chandigarh-travel-guide",
    title: "Capitol Complex Chandigarh: Le Corbusier's UNESCO Site Guide",
    excerpt:
      "The High Court, Secretariat, and Assembly that anchor Le Corbusier's masterplan — a UNESCO World Heritage Site, and the reason architects fly to Chandigarh.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Capitol Complex", "Chandigarh", "Le Corbusier", "UNESCO", "Open Hand Monument"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "sector-17-chandigarh-travel-guide",
    title: "Sector 17 Chandigarh: Plaza, Shopping & Nightlife Guide",
    excerpt:
      "Chandigarh's pedestrian-only city centre — fountains, cafés, Neelam Cinema, and the plaza every evening in the city eventually passes through.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sector 17", "Chandigarh", "Shopping", "City Guide"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "le-corbusier-centre-chandigarh-travel-guide",
    title: "Le Corbusier Centre Chandigarh: Museum Visit Guide",
    excerpt:
      "Original drawings, models, and photographs documenting how Le Corbusier planned an entire city from scratch — the essential primer before visiting the Capitol Complex.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Le Corbusier Centre", "Chandigarh", "Le Corbusier", "Architecture"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "government-museum-chandigarh-travel-guide",
    title: "Government Museum Chandigarh: Gandhara Art & Miniatures",
    excerpt:
      "Gandhara-era stone sculpture and Pahari miniature paintings in a quiet Sector 10 museum most tourists walk straight past.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Government Museum", "Chandigarh", "Sector 10", "Gandhara Art"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "japanese-garden-chandigarh-travel-guide",
    title: "Japanese Garden Chandigarh: Pagodas, Ponds & Best Time",
    excerpt:
      "Arched bridges, pagoda pavilions, and a still pond — Chandigarh's quietest themed garden, built around Japanese design principles.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Japanese Garden", "Chandigarh", "Sector 31", "Gardens"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "leisure-valley-chandigarh-travel-guide",
    title: "Leisure Valley Chandigarh: The City's Green Corridor Guide",
    excerpt:
      "A continuous green spine linking the Rose Garden, Bougainvillea Garden, and more — here's how to walk or cycle Chandigarh's Leisure Valley end to end.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Leisure Valley", "Chandigarh", "Gardens", "Walking"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "garden-of-fragrance-chandigarh-travel-guide",
    title: "Garden of Fragrance Chandigarh: Scented Plants & Braille Trail",
    excerpt:
      "A small garden built around scent rather than sight, with Braille signage for visually impaired visitors — one of Chandigarh's most thoughtful lesser-known gardens.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Garden of Fragrance", "Chandigarh", "Sector 36", "Gardens"],
    readTime: "8 min",
    featured: false,
  },
  {
    slug: "international-dolls-museum-chandigarh-travel-guide",
    title: "International Dolls Museum Chandigarh: Visit Guide",
    excerpt:
      "Dolls from dozens of countries in traditional costume, tucked inside the Bal Bhavan complex — Chandigarh's quirkiest, most kid-friendly museum stop.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["International Dolls Museum", "Chandigarh", "Sector 23", "Family Travel"],
    readTime: "8 min",
    featured: false,
  },
  {
    slug: "sector-22-chandigarh-travel-guide",
    title: "Sector 22 Chandigarh: Market, Stays & Local Life Guide",
    excerpt:
      "A working residential sector with a busy everyday market — Sector 22 is where budget stays and ordinary Chandigarh life meet.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sector 22", "Chandigarh", "Shopping", "Budget Stays"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "sector-26-chandigarh-travel-guide",
    title: "Sector 26 Chandigarh: Grain Market Food Street Guide",
    excerpt:
      "Chandigarh's best-known late-night food street sits beside its wholesale grain and vegetable mandi — butter chicken, tikkas, and kulchas till late.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sector 26", "Chandigarh", "Grain Market", "Food Street"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "sector-35-chandigarh-travel-guide",
    title: "Sector 35 Chandigarh: Market, Cafés & Student Vibe Guide",
    excerpt:
      "SCO markets, casual cafés, and a younger crowd — Sector 35 is Chandigarh's most contemporary commercial strip.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sector 35", "Chandigarh", "Cafes", "Shopping"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "terraced-garden-chandigarh-travel-guide",
    title: "Terraced Garden Chandigarh: Sector 33 Visit Guide",
    excerpt:
      "Stepped lawns and seasonal flowerbeds across multiple levels — a quieter picnic and photography alternative to the Rose Garden.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Terraced Garden", "Chandigarh", "Sector 33", "Gardens"],
    readTime: "8 min",
    featured: false,
  },
  {
    slug: "shanti-kunj-chandigarh-travel-guide",
    title: "Shanti Kunj Chandigarh: A Quiet Garden Near Rose Garden",
    excerpt:
      "A small, low-key green pocket near the Rose Garden — Chandigarh's simplest stop for a peaceful walk away from the crowds.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Shanti Kunj", "Chandigarh", "Sector 16", "Gardens"],
    readTime: "7 min",
    featured: false,
  },
  {
    slug: "bougainvillea-garden-chandigarh-travel-guide",
    title: "Bougainvillea Garden Chandigarh: Blooms & Best Time",
    excerpt:
      "Trellised arches and pruned bougainvillea shrubs bursting into colour every summer — a quiet, mostly-local garden along the Leisure Valley.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Bougainvillea Garden", "Chandigarh", "Sector 3", "Gardens"],
    readTime: "8 min",
    featured: false,
  },
  {
    slug: "chandigarh-botanical-garden-travel-guide",
    title: "Chandigarh Botanical Garden: Sarangpur Visit Guide",
    excerpt:
      "A sprawling, research-driven botanical garden on the city's outskirts — Chandigarh's most off-beat green escape, far removed from the manicured city gardens.",
    image: "/images/destinations/chandigarh/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Chandigarh Botanical Garden", "Sarangpur", "Chandigarh", "Nature"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "dadra-nagar-haveli-daman-diu-travel-guide",
    title: "Dadra & Nagar Haveli and Daman & Diu Travel Guide",
    excerpt:
      "A 16th-century Portuguese sea fort, near-empty beaches, and duty-free shopping — the complete guide to India's smallest, most overlooked Union Territory.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Diu", "Daman", "Silvassa"],
    readTime: "13 min",
    featured: true,
  },
  {
    slug: "jammu-kashmir-travel-guide",
    title: "Jammu & Kashmir Travel Guide: Srinagar, Gulmarg & Pahalgam",
    excerpt:
      "Houseboats on Dal Lake, gondola rides above the snow line, and valleys that earned Kashmir the name 'Paradise on Earth' — the complete guide.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Jammu & Kashmir", "Srinagar", "Gulmarg"],
    readTime: "15 min",
    featured: true,
  },
  {
    slug: "lakshadweep-island-travel-guide",
    title: "Lakshadweep Travel Guide: Permits, Islands & Best Time to Visit",
    excerpt:
      "Coral atolls barely a kilometre wide, turquoise lagoons, and some of India's clearest diving water — the complete guide to India's least-visited tropical paradise.",
    image: "/images/destinations/lakshadweep/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Lakshadweep", "Coral Islands", "Scuba Diving"],
    readTime: "12 min",
    featured: true,
  },
  {
    slug: "puducherry-french-quarter-travel-guide",
    title: "Puducherry Travel Guide: French Quarter, Auroville & Beaches",
    excerpt:
      "Mustard-yellow colonial villas, a seafront promenade closed to traffic, and the golden Matrimandir at Auroville — the complete guide to India's most European town.",
    image: "/images/destinations/puducherry/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Puducherry", "Tamil Nadu", "French Quarter"],
    readTime: "10 min",
    featured: true,
  },
  {
    slug: "puducherry-district-travel-guide",
    title: "Puducherry District Travel Guide: All 7 Towns & Attractions",
    excerpt:
      "Beyond the French Quarter and Auroville — a full town-by-town guide to Puducherry District, covering Villianur's ancient temple, Ariyankuppam's Arikamedu ruins and Chunnambar boat rides, Bahour's lake, Nettapakkam, and Oulgaret.",
    image: "/images/destinations/puducherry/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Puducherry District", "Villianur", "Ariyankuppam"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "karaikal-district-travel-guide",
    title: "Karaikal District Travel Guide: Temples, Beach & Cauvery Delta",
    excerpt:
      "Tirunallar's famous Saneeswaran Temple and Nala Theertham, Karaikal town's beach, lighthouse and Karaikal Ammaiyar Temple, and the quiet Cauvery delta villages of Neravy, Kottucherry, and Nedungadu.",
    image: "/images/destinations/hampi/virupaksha.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Karaikal District", "Tirunallar", "Puducherry"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "mahe-district-travel-guide",
    title: "Mahe District Travel Guide: Riverfront, Church & Malabar Coast",
    excerpt:
      "Mahe town's riverfront walkway, St. Teresa's Shrine, Tagore Park, beach and lighthouse, plus the quiet river villages of Palloor, Pandakkal, Chalakkara, and Parakkal on Kerala's Malabar coast.",
    image: "/images/destinations/kerala/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Mahe District", "Malabar Coast", "Puducherry"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "yanam-district-travel-guide",
    title: "Yanam District Travel Guide: Godavari Delta & French Heritage",
    excerpt:
      "St. Ann's Church, Yanam Ferry Road, the Godavari River, Yanam Tower and Rajiv Gandhi Beach, plus the quiet Godavari delta villages of Mettakur, Kolanka, and Kanakalapeta.",
    image: "/images/destinations/kerala/alleppey.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Yanam District", "Godavari Delta", "Puducherry"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "kavaratti-island-travel-guide",
    title: "Kavaratti Island Travel Guide: Lagoon, Diving & Ujra Mosque",
    excerpt:
      "Lakshadweep's capital and most developed inhabited island — Kavaratti Beach and Lagoon, the Marine Aquarium, the driftwood-ceilinged Ujra Mosque, scuba diving, snorkelling, and glass-bottom boat rides.",
    image: "/images/destinations/lakshadweep/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Kavaratti", "Lakshadweep", "Scuba Diving"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "agatti-island-travel-guide",
    title: "Agatti Island Travel Guide: Lagoon, Reefs & Diving Spots",
    excerpt:
      "Lakshadweep's gateway island — Agatti Beach and Lagoon, the Agatti Island Resort, coral reefs and diving spots, snorkelling sites, kayaking, glass-bottom boat rides, lagoon cruises, and sunset views.",
    image: "/images/destinations/lakshadweep/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Agatti", "Lakshadweep", "Scuba Diving"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "ziro-valley-arunachal-travel-guide",
    title: "Ziro Valley Travel Guide: Apatani Villages, Rice Fields & Festival",
    excerpt:
      "A UNESCO tentative heritage site in Arunachal — home to the Apatani tribe, terraced rice fields and one of India's best music festivals.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Ziro Valley", "Arunachal Pradesh", "Off-beat"],
    readTime: "11 min",
    featured: true,
  },
  {
    slug: "gokarna-beaches-travel-guide",
    title: "Gokarna Travel Guide: Best Beaches, Temples & Itinerary",
    excerpt:
      "A temple town with world-class beaches — Om Beach, Half Moon, and Paradise — linked by a cliffside trek and still a fraction as commercial as Goa.",
    image: "/images/destinations/coorg/coorg.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Gokarna", "Karnataka", "Beaches"],
    readTime: "9 min",
    featured: true,
  },
  {
    slug: "goa-beaches-travel-guide",
    title: "Goa Travel Guide: Best Beaches, North vs South & Itinerary",
    excerpt:
      "Portuguese-era churches, beach shacks, and a coastline that switches from party-loud to monastery-quiet within a few kilometres — the complete guide to Goa.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Goa", "Beaches"],
    readTime: "12 min",
    featured: true,
  },
  {
    slug: "udaipur-city-of-lakes-travel-guide",
    title: "Udaipur Travel Guide: City Palace, Lake Pichola & Itinerary",
    excerpt:
      "Palaces that appear to float on still water, whitewashed havelis and the most romantic skyline in Rajasthan — the complete guide to the City of Lakes.",
    image: "/images/destinations/jaisalmer/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Udaipur", "Rajasthan"],
    readTime: "10 min",
    featured: true,
  },
  {
    slug: "meghalaya-travel-guide",
    title: "Meghalaya Travel Guide: Living Root Bridges, Cherrapunji & More",
    excerpt:
      "Double-decker living root bridges, the cleanest river in Asia, and waterfalls that drop straight out of the clouds — the complete guide to India's wettest state.",
    image: "/images/destinations/meghalaya/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Meghalaya", "Northeast India"],
    readTime: "20 min",
    featured: true,
  },
  {
    slug: "manali-travel-guide",
    title: "Manali Travel Guide: Top Places, Itinerary & Insider Tips",
    excerpt:
      "The definitive guide to Manali — Rohtang Pass, Solang Valley, Old Manali cafes, and a 5-day itinerary that covers it all.",
    image: "/images/destinations/manali/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Manali", "Himachal Pradesh"],
    readTime: "16 min",
    featured: true,
  },
  {
    slug: "spiti-valley-travel-guide",
    title: "Spiti Valley: The Complete Travel Guide",
    excerpt:
      "A cold desert between Tibet and India — monasteries, fossils, and roads that will test your nerve and reward your soul.",
    image: "/images/destinations/spiti-valley/spiti-valley.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Spiti Valley", "Off-beat"],
    readTime: "22 min",
    featured: true,
  },
  {
    slug: "rishikesh-adventure-travel-guide",
    title: "Rishikesh Travel Guide: Adventure, Yoga, Rafting & More",
    excerpt:
      "India's adventure capital where white-water rafting meets Ganga aarti — everything you need for the perfect Rishikesh trip.",
    image: "/images/destinations/rishikesh/rishikesh.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Rishikesh", "Rafting", "Yoga"],
    readTime: "18 min",
    featured: true,
  },
  {
    slug: "coorg-travel-guide",
    title: "Coorg Travel Guide: Coffee, Waterfalls, Trekking & More",
    excerpt:
      "Misty coffee hills, thundering waterfalls, Nagarhole wildlife and Kodava warmth — South India's most quietly magnificent escape.",
    image: "/images/destinations/coorg/coorg.jpg",
    category: "Destination Guide",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Coorg", "Karnataka", "Coffee"],
    readTime: "17 min",
    featured: false,
  },
  {
    slug: "leh-ladakh-road-trip-travel-guide",
    title: "Leh Ladakh Road Trip Guide",
    excerpt:
      "Pangong Tso, Nubra Valley, Khardung La and 14 days on the most dramatic roads on earth.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Road Trip",
    categoryColor: "bg-stone-100 text-stone-700",
    tags: ["Ladakh", "Road Trip"],
    readTime: "26 min",
    featured: false,
  },
  {
    slug: "kasol-kheerganga-trek-travel-guide",
    title: "Kasol & Kheerganga: The Backpacker's Himalayan Trail",
    excerpt:
      "Follow the Parvati River to natural hot springs through pine forests and tiny Himalayan villages.",
    image: "/images/destinations/kasol/kasol.jpg",
    category: "Trekking",
    categoryColor: "bg-green-100 text-green-700",
    tags: ["Kasol", "Trekking"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "andaman-islands-travel-guide",
    title: "Andaman Islands Travel Guide: Beaches, Diving, Permits & Tips",
    excerpt:
      "Crystal-clear waters, pristine coral reefs, white sand beaches and the haunting history of Cellular Jail — the complete guide to the Andaman Islands.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Andaman", "Beaches", "Scuba Diving"],
    readTime: "20 min",
    featured: false,
  },
  {
    slug: "port-blair-andaman-travel-guide",
    title: "Sri Vijaya Puram (Port Blair) Travel Guide: Sights & Tips",
    excerpt:
      "The capital of the Andaman & Nicobar Islands and the gateway almost every traveller passes through — Cellular Jail, Corbyn's Cove, and the ferries onward.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Sri Vijaya Puram", "Port Blair", "Andaman Islands", "Cellular Jail", "Gateway City", "Ross Island", "North Bay Island"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "cellular-jail-andaman-travel-guide",
    title: "Cellular Jail Travel Guide: History, Timings & Light Show",
    excerpt:
      "A pentagonal British-era prison that became the most feared symbol of colonial punishment — and today, a moving National Memorial to India's freedom struggle.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Cellular Jail", "Kaala Pani", "Sri Vijaya Puram", "Port Blair", "Veer Savarkar", "Freedom Struggle", "National Memorial", "Light and Sound Show"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "havelock-island-andaman-travel-guide",
    title: "Swaraj Dweep (Havelock Island) Travel Guide: Beaches & Diving",
    excerpt:
      "The Andamans' most popular island — Radhanagar Beach, Elephant Beach snorkelling, and the region's biggest scuba diving hub, a 90-minute ferry from Port Blair.",
    image: "/images/destinations/andaman/havelock.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Havelock Island", "Swaraj Dweep", "Radhanagar Beach", "Elephant Beach", "Scuba Diving", "Andaman", "Ritchie's Archipelago", "Beaches"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "radhanagar-beach-andaman-travel-guide",
    title: "Radhanagar Beach Travel Guide: Timings, Sunset & Tips",
    excerpt:
      "Powder-white sand and shallow turquoise water on Havelock Island — once named one of Asia's best beaches by Time magazine, and still living up to it.",
    image: "/images/destinations/andaman/havelock.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Radhanagar Beach", "Beach No. 7", "Havelock Island", "Swaraj Dweep", "Sunset Point", "Andaman", "Best Beaches India"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "neil-island-andaman-travel-guide",
    title: "Shaheed Dweep (Neil Island) Travel Guide: Beaches & Tips",
    excerpt:
      "Andaman's slower, quieter island — Bharatpur Beach, a natural rock bridge at Laxmanpur, and a village pace that makes Neil Island the perfect wind-down after Havelock.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Neil Island", "Shaheed Dweep", "Bharatpur Beach", "Laxmanpur Beach", "Sitapur Beach", "Andaman Islands", "Island Hopping"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "ross-island-andaman-travel-guide",
    title: "Ross Island Travel Guide: Ruins, History & How to Visit",
    excerpt:
      "Once the 'Paris of the East' and the British administrative capital of the Andamans — now silent ruins overtaken by strangler figs, roamed by deer and peacocks.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Ross Island", "Netaji Subhas Chandra Bose Dweep", "Colonial Ruins", "Port Blair", "North Bay Island", "Andaman Islands", "Andaman History"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "baratang-andaman-travel-guide",
    title: "Baratang Island Travel Guide: Caves, Mud Volcano & Convoy Tips",
    excerpt:
      "A police-escorted convoy through a protected tribal reserve, a mangrove creek boat ride to limestone caves, and a bubbling mud volcano — Baratang is Andaman's strangest day trip.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Baratang Island", "Limestone Caves", "Mud Volcano", "Jarawa Tribal Reserve", "Andaman Trunk Road", "Parrot Island", "Day Trip"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "diglipur-andaman-travel-guide",
    title: "Diglipur Travel Guide: Saddle Peak, Kalipur & North Andaman",
    excerpt:
      "The farthest major town from Port Blair, and the gateway to the highest point in the Andamans, a turtle-nesting beach, and a twin-island sandbar most tourists never reach.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Diglipur", "Saddle Peak", "Kalipur Beach", "Ross and Smith Islands", "North Andaman", "Trekking", "Off-beat"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "ross-and-smith-islands-andaman-travel-guide",
    title: "Ross & Smith Islands Travel Guide: Sandbar, Permits & Tips",
    excerpt:
      "Two islands, one natural sandbar you can walk across at low tide — Ross & Smith is North Andaman's most pristine, least-crowded beach escape.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Ross & Smith Islands", "Diglipur", "North Andaman", "Sandbar", "Off-beat Islands", "Andaman Islands"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "kalipur-andaman-travel-guide",
    title: "Kalipur Beach Travel Guide: Turtles, Saddle Peak & Tips",
    excerpt:
      "A quiet turtle-nesting beach near Diglipur and the starting point for the Saddle Peak trek — Kalipur is North Andaman at its calmest.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Kalipur", "Diglipur", "North Andaman", "Turtle Nesting", "Saddle Peak", "Andaman Islands"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "north-bay-island-andaman-travel-guide",
    title: "North Bay Island Andaman: Coral, Sea Walking & Visit Guide",
    excerpt:
      "A short boat ride from Port Blair — glass-bottom boats, snorkelling, and a helmet sea walk over coral, usually paired with a Ross Island visit.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["North Bay Island", "Andaman", "Sea Walking", "Snorkelling", "Ross Island", "Port Blair", "Coral Reef", "Day Trip"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "jolly-buoy-island-andaman-travel-guide",
    title: "Jolly Buoy Island Andaman: Marine Park Visit Guide",
    excerpt:
      "Some of the clearest water and healthiest coral in the Andamans, protected inside a marine national park — with strict visitor limits and a seasonal closure.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Jolly Buoy Island", "Andaman", "Mahatma Gandhi Marine National Park", "Wandoor", "Snorkelling", "Coral Reef", "Port Blair"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "chidiya-tapu-andaman-travel-guide",
    title: "Chidiya Tapu Travel Guide: Sunset Point, Birds & Tips",
    excerpt:
      "The southernmost tip of South Andaman — mangroves, birdlife, a small biological park, and consistently rated one of the best sunsets in the islands.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Chidiya Tapu", "Andaman", "South Andaman", "Sunset Point", "Bird Island", "Munda Pahad Beach", "Off-beat"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "mount-manipur-andaman-travel-guide",
    title: "Mount Manipur (Mount Harriet) Travel Guide: Trek & Views",
    excerpt:
      "The second-highest point in the Andamans, across the harbour from Port Blair — colonial-era ruins, forest trails, and panoramic views over Ross Island and North Bay.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Trekking",
    categoryColor: "bg-green-100 text-green-700",
    tags: ["Mount Manipur", "Mount Harriet", "Andaman", "Trekking", "Port Blair", "Colonial History", "Viewpoint"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "rangat-andaman-travel-guide",
    title: "Rangat Andaman Travel Guide: Cuthbert Bay & Long Island",
    excerpt:
      "Middle Andaman's practical halfway town — a turtle-nesting beach, a mangrove boardwalk, and the jetty for Long Island's untouched shores.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Rangat", "Middle Andaman", "Cuthbert Bay", "Long Island", "Andaman Trunk Road", "North Andaman"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "mayabunder-andaman-travel-guide",
    title: "Mayabunder Travel Guide: Interview Island & Karmatang Beach",
    excerpt:
      "North Andaman's quietest gateway town — feral elephants on a protected island, a turtle-nesting beach, and a genuine break from the Havelock/Neil circuit.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Mayabunder", "North Andaman", "Interview Island", "Karmatang Beach", "Wildlife", "Off the Beaten Path"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "little-andaman-travel-guide",
    title: "Little Andaman Travel Guide: Butler Bay, Surfing & Tips",
    excerpt:
      "India's most consistent surf break, two forest waterfalls, and a six-to-eight-hour ferry crossing — Little Andaman is the Andamans' furthest-flung island stop.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Little Andaman", "Butler Bay", "Surfing", "Waterfalls", "Onge Tribe", "Offbeat Islands", "Andaman"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "long-island-andaman-travel-guide",
    title: "Long Island Andaman: Lalaji Bay Beach Travel Guide",
    excerpt:
      "A pristine, little-visited beach reached through mangrove forest, minimal infrastructure, and none of the Havelock crowds — Long Island is Middle Andaman's quiet secret.",
    image: "/images/destinations/andaman/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Long Island", "Lalaji Bay Beach", "Merk Bay", "Middle Andaman", "Offbeat Islands", "Rangat", "Andaman"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "hampi-travel-guide",
    title: "Hampi Travel Guide: Ruins, Boulders, Temples & Tips",
    excerpt:
      "The extraordinary ruins of the Vijayanagara Empire scattered across a surreal boulder landscape — the complete guide to Hampi.",
    image: "/images/destinations/hampi/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Hampi", "Karnataka", "Heritage"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "kerala-backwaters-travel-guide",
    title: "Kerala Backwaters Guide: Houseboats, Routes, Villages & Tips",
    excerpt:
      "A 900-km network of lagoons, canals and lakes explored by houseboat — the complete guide to Kerala's backwaters.",
    image: "/images/destinations/kerala/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Kerala", "Backwaters", "Houseboat"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "rajasthan-desert-travel-guide",
    title: "Jaisalmer & Thar Desert Travel Guide: Fort, Camel Safari & Tips",
    excerpt:
      "A living medieval fort rising from the Thar Desert, camel safaris into the dunes and the most spectacular havelis in Rajasthan — the complete guide to Jaisalmer.",
    image: "/images/destinations/jaisalmer/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Jaisalmer", "Rajasthan", "Desert Safari"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "valley-of-flowers-travel-guide",
    title: "Valley of Flowers Trek Guide: Permits, Routes, Best Time & Tips",
    excerpt:
      "A meadow of 300+ Himalayan wildflowers that blooms for just 8 weeks a year — the complete guide to India's most extraordinary trek.",
    image: "/images/destinations/manali/hero.jpg",
    category: "Trekking",
    categoryColor: "bg-green-100 text-green-700",
    tags: ["Valley of Flowers", "Uttarakhand", "Trekking"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "leh-travel-guide",
    title: "Leh Travel Guide: Leh Palace, Market, Shanti Stupa & Tips",
    excerpt:
      "A whitewashed old town under a ruined nine-storey palace, at 3,524 metres — Leh Palace, the bazaar, Shanti Stupa, and everything you need to explore the capital of Ladakh itself.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Leh", "Ladakh", "Old Town", "High Altitude", "Monasteries"],
    readTime: "17 min",
    featured: false,
  },
  {
    slug: "nubra-valley-travel-guide",
    title: "Nubra Valley Travel Guide: Sand Dunes, Camels & Cold Desert",
    excerpt:
      "Cross the world's second-highest motorable pass into a valley where sand dunes meet snow peaks, Bactrian camels roam ancient Silk Route trails, and a 32-metre Buddha watches over the Shyok River.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Nubra Valley", "Ladakh", "Khardung La", "Sand Dunes", "Ladakh Monasteries"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "pangong-lake-travel-guide",
    title: "Pangong Lake Travel Guide: Routes, Permits, Camping & Tips",
    excerpt:
      "A saline lake at 4,225 metres that turns turquoise to violet across a single afternoon — here's how to reach it, camp on its shore, and see it away from the crowds.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Pangong Lake", "Ladakh", "Chang La", "Camping", "High Altitude", "Road Trip"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "hunder-travel-guide",
    title: "Hunder Travel Guide: Nubra Valley's Sand Dunes & Camel Safari",
    excerpt:
      "Silver sand dunes, double-humped Bactrian camels, and snow peaks rising from a cold desert — Hunder in Nubra Valley is Ladakh's strangest, most beautiful contradiction.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Hunder", "Nubra Valley", "Ladakh", "Bactrian Camel Safari", "Cold Desert"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "tso-moriri-travel-guide",
    title: "Tso Moriri Travel Guide: Ladakh's Most Pristine High-Altitude Lake",
    excerpt:
      "A sapphire lake at 4,522 metres on the remote Rupshu plateau, ringed by bare mountains and grazed by wild kiang — Tso Moriri is the Ladakh lake that stayed wild.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Tso Moriri", "Ladakh", "Rupshu Plateau", "Korzok", "High Altitude Lake"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "kargil-travel-guide",
    title: "Kargil Travel Guide: Gateway to Zanskar & the Srinagar-Leh Highway",
    excerpt:
      "Halfway between Srinagar and Leh, where Balti Muslim and Ladakhi Buddhist worlds meet amid apricot orchards — Kargil is the highway town most travellers rush through, and the doorway to remote Zanskar.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Kargil", "Ladakh", "Srinagar-Leh Highway", "Balti Culture", "Zanskar"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "drass-travel-guide",
    title: "Drass Travel Guide: Kargil War Memorial & the Gateway to Ladakh",
    excerpt:
      "The second-coldest inhabited place on Earth, and the town that stands quietly at the foot of the Kargil War Memorial — a stopover on the Srinagar-Leh highway you won't forget.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Drass", "Ladakh", "Kargil War Memorial", "Zoji La", "Kargil"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "zanskar-valley-travel-guide",
    title: "Zanskar Valley Travel Guide: Chadar Trek, Phugtal Monastery & Padum",
    excerpt:
      "Cut off from the world for eight months a year by snow, Zanskar is Ladakh's last true frontier — home to the legendary frozen-river Chadar Trek and the cliffside Phugtal Monastery.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Trekking",
    categoryColor: "bg-green-100 text-green-700",
    tags: ["Zanskar Valley", "Ladakh", "Trekking", "Chadar Trek", "Phugtal Monastery"],
    readTime: "19 min",
    featured: false,
  },
  {
    slug: "hanle-travel-guide",
    title: "Hanle Travel Guide: Dark Sky Reserve, Observatory & Stargazing",
    excerpt:
      "A village at 4,500 metres on the Changthang plateau where the Milky Way is visible to the naked eye — the complete guide to India's first Dark Sky Reserve and the Indian Astronomical Observatory.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Hanle", "Ladakh", "Dark Sky Reserve", "Stargazing", "Changthang"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "turtuk-travel-guide",
    title: "Turtuk Travel Guide: Ladakh's Last Balti Village Before the LOC",
    excerpt:
      "A Balti village of stone houses and apricot orchards on the Shyok River, under Pakistani control until 1971 and closed to outsiders until 2010 — Turtuk is unlike anywhere else in Ladakh.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Turtuk", "Ladakh", "Nubra Valley", "Balti Culture", "Homestays"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "lamayuru-travel-guide",
    title: "Lamayuru Travel Guide: Moonland, Monastery & How to Visit",
    excerpt:
      "Ladakh's oldest monastery perches above a landscape so eroded it's simply called the Moonland — here's how to see it right, from the Yuru Kabgyat festival to the short treks that begin at its gates.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Lamayuru", "Ladakh", "Moonland", "Monastery"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "hemis-travel-guide",
    title: "Hemis Travel Guide: Monastery, Festival & Snow Leopard Country",
    excerpt:
      "Ladakh's largest and wealthiest monastery, its most spectacular masked-dance festival, and the wild high-altitude kingdom of the snow leopard — all hidden in one secluded valley.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Hemis", "Ladakh", "Monastery", "Snow Leopard", "Festival"],
    readTime: "18 min",
    featured: false,
  },
  {
    slug: "thiksey-travel-guide",
    title: "Thiksey Travel Guide: Monastery, Morning Prayers & Maitreya Buddha",
    excerpt:
      "Twelve storeys of whitewashed walls climb a hillside above the Indus like a mini Potala Palace — home to a 15-metre golden Buddha and the most spellbinding 6 AM prayer ceremony in Ladakh.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Thiksey", "Ladakh", "Leh", "Monastery", "Buddhism"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "khardung-la-travel-guide",
    title: "Khardung La Travel Guide: Height, Route, Permits & Tips",
    excerpt:
      "At 5,359 metres, the air thins, prayer flags snap in the wind, and the road to Nubra Valley climbs above the clouds — everything you need to cross Khardung La safely and unforgettably.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Khardung La", "Ladakh", "Nubra Valley", "High Altitude", "Road Trip"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "dha-hanu-travel-guide",
    title: "Dha-Hanu Travel Guide: Ladakh's Aryan Valley & the Brokpa People",
    excerpt:
      "Along a quiet bend of the Indus, the Brokpa villages of Dha, Hanu, Garkone and Darchik hold on to a language, dress, and way of life found nowhere else in India — a guide to visiting them carefully, and on their own terms.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Dha-Hanu", "Ladakh", "Aryan Valley", "Brokpa", "Offbeat India", "Indus Valley", "Cultural Travel"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "padum-travel-guide",
    title: "Padum Travel Guide: Zanskar Valley's Historic Capital Town",
    excerpt:
      "A dusty bazaar town where two rivers meet, Padum is Zanskar's historic capital and the essential base for its monasteries, royal ruins, and legendary high-altitude treks.",
    image: "/images/destinations/leh-ladakh/leh-ladakh.jpg",
    category: "Trekking",
    categoryColor: "bg-green-100 text-green-700",
    tags: ["Padum", "Zanskar Valley", "Ladakh", "Monasteries", "High Altitude"],
    readTime: "18 min",
    featured: false,
  },
  {
    slug: "srinagar-travel-guide",
    title: "Srinagar Travel Guide: Dal Lake, Houseboats & Mughal Gardens",
    excerpt:
      "Wake to a shikara gliding through Dal Lake's floating market, spend a night on a carved wooden houseboat, and walk the Mughal gardens the Zabarwan hills were built to frame.",
    image: "/images/destinations/jammu-kashmir/dal.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Srinagar", "Jammu and Kashmir", "Dal Lake", "Houseboats", "Mughal Gardens", "Kashmir"],
    readTime: "17 min",
    featured: false,
  },
  {
    slug: "gulmarg-travel-guide",
    title: "Gulmarg Travel Guide: Gondola, Skiing & Meadows",
    excerpt:
      "A cable car that climbs past 3,900 metres, ski slopes that rival anywhere in the Himalayas, and meadows that turn green the moment the snow retreats — Gulmarg does double duty as India's top winter and summer mountain escape.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Gulmarg", "Jammu and Kashmir", "Kashmir", "Skiing", "Gondola", "Meadows"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "pahalgam-travel-guide",
    title: "Pahalgam Travel Guide: Betaab Valley, Aru & Chandanwari",
    excerpt:
      "A pine-forested valley along the Lidder River where Bollywood found its favourite backdrop and pilgrims begin the Amarnath Yatra — Betaab Valley, Aru, and Chandanwari, all in one gentle Kashmir escape.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Pahalgam", "Jammu and Kashmir", "Betaab Valley", "Aru Valley", "Chandanwari", "Amarnath Yatra", "Lidder River"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "sonamarg-travel-guide",
    title: "Sonamarg Travel Guide: Thajiwas Glacier & How to Visit",
    excerpt:
      "A glacier you can walk to, a river valley that never stops moving, and the last stretch of Kashmir before the road climbs into Ladakh — meet Sonamarg, the Meadow of Gold.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Sonamarg", "Jammu and Kashmir", "Thajiwas Glacier", "Zoji La", "Kashmir", "Ladakh Gateway"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "jammu-travel-guide",
    title: "Jammu Travel Guide: Temples, Forts & Winter Capital",
    excerpt:
      "Gold-topped temple spires, a fort above the Tawi River, and Dogra hospitality — discover Jammu, the City of Temples and winter capital of J&K.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Jammu", "Jammu and Kashmir", "Temples", "Bahu Fort", "Raghunath Temple", "Dogra Cuisine"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "katra-travel-guide",
    title: "Katra & Vaishno Devi Yatra Guide: Route, Tips & Stay",
    excerpt:
      "The complete gateway-town guide to the Vaishno Devi Yatra — the 13 km trek from Katra to Bhawan, registration, helicopter booking, and where to rest before the climb.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Katra", "Vaishno Devi", "Jammu and Kashmir", "Pilgrimage", "Trekking"],
    readTime: "17 min",
    featured: false,
  },
  {
    slug: "gurez-valley-travel-guide",
    title: "Gurez Valley Travel Guide: Kashmir's Hidden Border Valley",
    excerpt:
      "A remote Dard-Shin valley along the Kishanganga River, cradled beneath the cone of Habba Khatoon Peak — closed to civilian tourism for decades, and still one of the quietest corners of Kashmir.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Gurez Valley", "Jammu and Kashmir", "Habba Khatoon", "Dawar", "Tulail Valley", "Offbeat Kashmir"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "doodhpathri-travel-guide",
    title: "Doodhpathri Travel Guide: Kashmir's Valley of Milk",
    excerpt:
      "A rolling green meadow ringed by pine forest, a stream that froths milky-white over its stones, and a fraction of the crowds at Gulmarg — Kashmir's quietest valley, best done as an unhurried day trip from Srinagar.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Doodhpathri", "Jammu and Kashmir", "Kashmir Meadows", "Budgam", "Off-beat Kashmir", "Srinagar Day Trips"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "yusmarg-travel-guide",
    title: "Yusmarg Travel Guide: Meadow of Jesus & Nilnag Lake",
    excerpt:
      "A quiet, pine-fringed meadow in Budgam where the crowds thin out — pony rides across open grassland, a glacial lake through the pines, and a Sufi shrine on the way.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Yusmarg", "Jammu and Kashmir", "Nilnag Lake", "Kashmir", "Budgam", "Charar-e-Sharief"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "aharbal-travel-guide",
    title: "Aharbal Waterfall Travel Guide: Kashmir's Niagara",
    excerpt:
      "A wide, roaring curtain of water on the Veshaw River, framed by pine forest — Aharbal is the waterfall Kashmiris proudly call their own Niagara.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Aharbal", "Jammu and Kashmir", "Waterfall", "Kulgam", "Kashmir Waterfalls", "Veshaw River"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "patnitop-travel-guide",
    title: "Patnitop Travel Guide: Paragliding, Pines & Best Time",
    excerpt:
      "A pine-forested plateau on the Jammu-Srinagar highway, three hours from Jammu — paragliding launches at Sanasar, forest walks, and one of North India's closest winter snow escapes.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Adventure",
    categoryColor: "bg-amber-100 text-amber-700",
    tags: ["Patnitop", "Jammu and Kashmir", "Sanasar", "Paragliding", "Nathatop", "Weekend Getaway", "Hill Station"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "bhaderwah-travel-guide",
    title: "Bhaderwah Travel Guide: J&K's Mini Kashmir",
    excerpt:
      "Terraced meadows, glacier-fed valleys, and a snow point toward Chamba — Bhaderwah is the quiet Doda district town locals call Mini Kashmir.",
    image: "/images/destinations/jammu-kashmir/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Bhaderwah", "Jammu and Kashmir", "Mini Kashmir", "Doda District", "Jai Valley", "Padri"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "new-delhi-travel-guide",
    title: "New Delhi Travel Guide: India Gate, Rajpath & More",
    excerpt:
      "Wide colonial avenues, a president's palace, and a parliament at the centre of the world's largest democracy — the complete guide to New Delhi's Lutyens-era core.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["New Delhi", "Delhi", "India Gate", "Kartavya Path", "Rashtrapati Bhavan"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "old-delhi-travel-guide",
    title: "Old Delhi Travel Guide: Red Fort, Jama Masjid & Food",
    excerpt:
      "Shahjahanabad, Shah Jahan's 17th-century walled capital — Red Fort, India's largest mosque, cycle-rickshaw lanes, havelis, bazaars, and a street food trail running for well over a century.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Old Delhi", "Delhi", "Red Fort", "Jama Masjid", "Chandni Chowk", "Street Food", "Shahjahanabad"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "mehrauli-delhi-travel-guide",
    title: "Mehrauli Travel Guide: Qutub Minar & Ancient Delhi",
    excerpt:
      "Delhi's oldest continuously inhabited settlement — Qutub Minar, the rust-resistant Iron Pillar, a forest full of forgotten tombs, and 800+ years of layered history in one walkable quarter.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Mehrauli", "Delhi", "Qutub Minar", "Iron Pillar", "Mehrauli Archaeological Park", "UNESCO World Heritage Site", "Heritage Walk"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "south-delhi-travel-guide",
    title: "South Delhi Travel Guide: Best Areas & Things to Do",
    excerpt:
      "Hauz Khas, Greater Kailash, Saket, Vasant Kunj, Mehrauli, Lodhi Garden, and Chhatarpur Temple — a guide to Delhi's most affluent, green, and heritage-dense quarter, area by area.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["South Delhi", "Delhi", "Hauz Khas", "Qutub Minar", "Greater Kailash"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "hauz-khas-delhi-travel-guide",
    title: "Hauz Khas Travel Guide: Village, Deer Park & Fort Ruins",
    excerpt:
      "A 700-year-old royal reservoir and madrasa ruins sit right beside Delhi's trendiest boutique-and-nightlife village — the complete Hauz Khas guide.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Hauz Khas", "Delhi", "Deer Park", "Hauz Khas Village", "Nightlife", "South Delhi"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "nizamuddin-delhi-travel-guide",
    title: "Nizamuddin Travel Guide: Dargah, Qawwali & Humayun's Tomb",
    excerpt:
      "A 700-year-old Sufi shrine still alive with devotion, Thursday night qawwali, and Humayun's Tomb next door — inside Delhi's most spiritually alive neighbourhood.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Nizamuddin", "Delhi", "Sufi Shrine", "Qawwali", "Humayun's Tomb"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "akshardham-delhi-travel-guide",
    title: "Akshardham Temple Delhi: Timings, Tickets & Guide",
    excerpt:
      "Timings, ticket pricing, the Sahaj Anand Water Show, the boat ride, strict entry rules, and a full half-day plan for visiting Akshardham in Delhi.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Akshardham", "Delhi", "Hindu Temple", "Water Show", "Family-Friendly"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "tughlaqabad-delhi-travel-guide",
    title: "Tughlaqabad Fort Travel Guide: Delhi's Cursed City",
    excerpt:
      "Delhi's massive, mostly-empty 14th-century fort ruins built by Sultan Ghiyasuddin Tughlaq — sloping ramparts, 13 gates, an underground citadel, and the legendary curse of Nizamuddin Auliya.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Tughlaqabad", "Delhi", "Fort Ruins", "Delhi Sultanate", "Off-Beat Delhi"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "connaught-place-delhi-travel-guide",
    title: "Connaught Place Guide: Shopping, Food & Nightlife",
    excerpt:
      "The Inner, Middle & Outer Circle layout, Central Park, Palika Bazaar, old-school eateries and nightlife — the complete guide to Delhi's Georgian-era commercial hub.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Connaught Place", "Delhi", "Rajiv Chowk", "Central Park", "Palika Bazaar", "Shopping", "Nightlife"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "chandni-chowk-delhi-travel-guide",
    title: "Chandni Chowk: Delhi's Legendary Food Walk & Bazaar Guide",
    excerpt:
      "A 350-year-old market built by Jahanara Begum — Kinari Bazaar, Khari Baoli's spice trade, and the legendary Chandni Chowk street food walk.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Chandni Chowk", "Delhi", "Old Delhi", "Street Food", "Khari Baoli"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "majnu-ka-tilla-delhi-travel-guide",
    title: "Majnu Ka Tilla Guide: Delhi's Tibetan Colony",
    excerpt:
      "A slice of Tibet on the banks of the Yamuna — momos, thukpa, Korean cafés, prayer-flag markets, and Delhi's most concentrated Tibetan cultural enclave.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Majnu Ka Tilla", "Delhi", "Little Tibet", "Tibetan Colony", "Momos"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "chanakyapuri-delhi-travel-guide",
    title: "Chanakyapuri Guide: Delhi's Diplomatic Enclave",
    excerpt:
      "An honest look at Chanakyapuri — Delhi's diplomatic enclave of embassies, Nehru Park, tree-lined boulevards, and nearby Gandhi Smriti and Teen Murti Bhavan.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Chanakyapuri", "Delhi", "Nehru Park", "Diplomatic Enclave", "Gandhi Smriti", "Teen Murti Bhavan", "City Guide"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "lodhi-garden-delhi-travel-guide",
    title: "Lodhi Garden: Delhi's Tombs, Timings & Complete Visit Guide",
    excerpt:
      "90 acres of landscaped green in the middle of South Delhi, dotted with 500-year-old tombs from the Sayyid and Lodi dynasties — Delhi's favourite morning-walk park doubling as an open-air museum.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Lodhi Garden", "Delhi", "Lodi Dynasty", "Khan Market", "South Delhi", "Heritage Walk"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "vasant-kunj-delhi-travel-guide",
    title: "Vasant Kunj Guide: Malls, Shopping & Nature Nearby",
    excerpt:
      "Delhi's upscale mall district next to IGI Airport — Ambience Mall, DLF Promenade, DLF Emporio, and the surprisingly wild Asola Bhatti forest just beyond it.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Vasant Kunj", "Delhi", "Ambience Mall", "DLF Emporio", "Asola Bhatti Wildlife Sanctuary", "Airport Guide", "Shopping"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "dwarka-delhi-travel-guide",
    title: "Dwarka, Delhi Travel Guide: Sub-City & ISKCON Temple",
    excerpt:
      "One of Asia's largest planned sub-cities, minutes from IGI Airport — Dwarka's ISKCON Temple, sector markets, and metro access. Not Dwarka, Gujarat.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Dwarka Delhi", "Delhi", "ISKCON Temple Dwarka", "South West Delhi"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "karol-bagh-delhi-travel-guide",
    title: "Karol Bagh Travel Guide: Shopping, Markets & Budget Hotels",
    excerpt:
      "A pedestrianised bazaar on Ajmal Khan Road, Gaffar Market's electronics stalls, and one of Delhi's densest budget-hotel clusters — the complete guide to shopping, eating, and staying in Karol Bagh.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Karol Bagh", "Delhi", "Ajmal Khan Road", "Gaffar Market", "Shopping", "Budget Hotels"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "lajpat-nagar-delhi-travel-guide",
    title: "Lajpat Nagar Travel Guide: Central Market & More",
    excerpt:
      "One of Delhi's most beloved shopping neighbourhoods — Central Market's ethnic wear and bridal shopping, the Tibetan Market next door, bargaining etiquette, and a practical half-day plan.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Lajpat Nagar", "Delhi", "Central Market", "Tibetan Market", "Shopping"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "sarojini-nagar-delhi-travel-guide",
    title: "Sarojini Nagar Market Guide: Shopping & Bargaining Tips",
    excerpt:
      "A maze of stalls selling export-surplus clothing, footwear, and accessories at rock-bottom prices — how to shop Sarojini Nagar well and bargain like a local.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Sarojini Nagar", "Delhi", "Street Shopping", "Export Surplus", "Bargaining"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "paharganj-delhi-travel-guide",
    title: "Paharganj Travel Guide: Main Bazaar & Budget Stays",
    excerpt:
      "Delhi's classic backpacker district — Main Bazaar shopping, budget guesthouses, cheap eats, and honest safety tips, all right beside New Delhi Railway Station.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Paharganj", "Delhi", "Main Bazaar", "Backpacking", "Budget Travel"],
    readTime: "15 min",
    featured: false,
  },
  {
    slug: "kashmere-gate-delhi-travel-guide",
    title: "Kashmere Gate Travel Guide: History, 1857 Sites & the ISBT Hub",
    excerpt:
      "Shahjahanabad's northern gate, an 1857 Revolt battleground, St. James' Church, Nicholson Cemetery, and Delhi's biggest ISBT transit hub — with a suggested heritage-walk plan.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Kashmere Gate", "Delhi", "1857 Revolt", "Old Delhi", "St. James Church", "ISBT"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "rohini-delhi-travel-guide",
    title: "Rohini Delhi Guide: Japanese Park & Family Outings",
    excerpt:
      "A practical Rohini guide — Delhi's huge DDA residential sub-city known for Japanese Park, Adventure Island, and extensive Metro coverage, not for heritage sightseeing.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Rohini", "Delhi", "Japanese Park", "Adventure Island", "North West Delhi", "Family Outing"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "janakpuri-delhi-travel-guide",
    title: "Janakpuri Delhi Guide: Parks, Markets & Transport",
    excerpt:
      "A practical guide to Janakpuri, West Delhi's planned residential colony — District Park, local markets, the Janakpuri West Metro interchange, and why it's worth knowing about.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Janakpuri", "Delhi", "West Delhi", "Delhi Metro", "District Park"],
    readTime: "8 min",
    featured: false,
  },
  {
    slug: "laxmi-nagar-delhi-travel-guide",
    title: "Laxmi Nagar, Delhi: Market, Coaching Hub & Local Food Guide",
    excerpt:
      "A local's guide to Laxmi Nagar, Delhi — East Delhi's dense market-and-coaching neighbourhood, its UPSC/SSC institute ecosystem, PG accommodation, street food, and how to reach it by metro.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Laxmi Nagar", "Delhi", "UPSC Coaching", "Nirman Vihar Metro", "East Delhi", "Student Life", "Local Market"],
    readTime: "13 min",
    featured: false,
  },
  {
    slug: "najafgarh-delhi-travel-guide",
    title: "Najafgarh Delhi Guide: History, Jheel & Sehwag",
    excerpt:
      "An honest guide to Najafgarh — Nawab Najaf Khan's 18th-century fort roots, the shrinking Najafgarh Jheel wetland, and its fame as Virender Sehwag's hometown.",
    image: "/images/destinations/jaisalmer/fort.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Najafgarh", "Delhi", "Najafgarh Jheel", "Virender Sehwag", "South West Delhi"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "diu-travel-guide",
    title: "Diu Travel Guide: Beaches, Fort & Weekend Trip",
    excerpt:
      "A former Portuguese colony off Gujarat's coast — Diu Fort, quiet beaches, old-town churches, duty-free liquor, and a full 2-day itinerary.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Diu", "Daman and Diu", "Diu Fort", "Nagoa Beach", "Portuguese Heritage", "Island Getaway"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "daman-travel-guide",
    title: "Daman Travel Guide: Forts, Beaches & Weekend Trip",
    excerpt:
      "A former Portuguese enclave split by the Daman Ganga river into Moti Daman and Nani Daman — forts, quiet beaches, duty-free shopping, and a full 2-day itinerary for this Gujarat coastal getaway.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Daman", "Daman and Diu", "Moti Daman", "Nani Daman", "Portuguese Heritage", "Weekend Trip", "Gujarat Coast"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "silvassa-travel-guide",
    title: "Silvassa Travel Guide: Lakes, Forests & Tribal Culture",
    excerpt:
      "Capital of Dadra & Nagar Haveli — Dudhni's lake and Tribal Museum, Khanvel's gardens, Satmaliya Deer Sanctuary, Madhuban Dam, Warli tribal art, and a full 2-day itinerary for this green, inland weekend escape near Mumbai.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Destination Guide",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Silvassa", "Dadra and Nagar Haveli", "Dudhni", "Khanvel", "Warli Art", "Weekend Trip"],
    readTime: "14 min",
    featured: false,
  },
  {
    slug: "dudhni-travel-guide",
    title: "Dudhni Lake Travel Guide: Boating Near Silvassa",
    excerpt:
      "A short drive from Silvassa, Dudhni is a quiet reservoir village on the Madhuban Dam backwaters — motorboat rides, picnic spots, and an easy half-day escape from town.",
    image: "/images/destinations/goa/beach.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Dudhni", "Dadra and Nagar Haveli", "Silvassa", "Madhuban Dam", "Boating"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "nagoa-beach-travel-guide",
    title: "Nagoa Beach Diu: Water Sports, Timings & Tips",
    excerpt:
      "A horseshoe-shaped bay of calm water, coconut-lined promenade and Diu's only real watersports scene — everything you need for a half-day at Nagoa Beach.",
    image: "/images/destinations/goa/beach.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Nagoa Beach", "Diu", "Daman and Diu", "Water Sports", "Swimming"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "jampore-beach-travel-guide",
    title: "Jampore Beach Daman: Camel Rides, Timings & Tips",
    excerpt:
      "A long, quiet, casuarina-lined beach south of Moti Daman — camel and pony rides, sunset walks, and honest advice on swimming conditions.",
    image: "/images/destinations/goa/beach.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Jampore Beach", "Daman", "Daman and Diu", "Moti Daman", "Camel Ride", "Sunset Point"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "devka-beach-travel-guide",
    title: "Devka Beach Daman: Promenade, Rides & Activities",
    excerpt:
      "Daman's busiest, most developed beach — a landscaped seafront promenade, garden, rock-climbing wall, camel rides, and food stalls, with honest advice on the rocky shoreline and best evening visit plan.",
    image: "/images/destinations/goa/beach.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Devka Beach", "Daman", "Daman and Diu", "Nani Daman", "Beaches", "Family Trip", "Sunset Point"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "diu-fort-travel-guide",
    title: "Diu Fort Travel Guide: History, Timings & Tips",
    excerpt:
      "A 16th-century Portuguese sea fort with a seawater-filled moat, original cannons, and one of the best sunset spots on India's west coast — the complete guide to Diu Fort.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Diu Fort", "Diu", "Daman and Diu", "Portuguese Heritage", "Sea Fort", "Heritage Sites", "Sunset Point"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "moti-daman-travel-guide",
    title: "Moti Daman Travel Guide: Old Town, Churches & Fort",
    excerpt:
      "Massive fort walls, a gilded church altar, and the quiet lanes of old Portuguese administration — inside Moti Daman, the grander, southern half of Daman's historic riverside old town.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Moti Daman", "Daman", "Daman and Diu", "Bom Jesus Church", "Fort of St Jerome", "Portuguese Heritage", "Old Town"],
    readTime: "12 min",
    featured: false,
  },
  {
    slug: "naida-caves-travel-guide",
    title: "Naida Caves Diu: Photography Spot & Visit Guide",
    excerpt:
      "A maze of sun-dappled sandstone chambers near Diu Fort — natural skylights, root-covered walls, and one of Diu's best offbeat photography spots.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Naida Caves", "Diu", "Daman and Diu", "Diu Fort", "Photography", "Hidden Gems"],
    readTime: "8 min",
    featured: false,
  },
  {
    slug: "ghoghla-beach-travel-guide",
    title: "Ghoghla Beach Diu: Water Sports & Camping Guide",
    excerpt:
      "A long, wide beach where Diu island meets the Gujarat mainland — jet-skiing, banana boat rides, beach camping, and a quieter alternative to Nagoa.",
    image: "/images/destinations/goa/beach.jpg",
    category: "Beaches",
    categoryColor: "bg-sky-100 text-sky-700",
    tags: ["Ghoghla Beach", "Diu", "Daman and Diu", "Water Sports", "Beach Camping"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "khanvel-travel-guide",
    title: "Khanvel Travel Guide: Gardens & Nature Escape",
    excerpt:
      "A small forested town near Silvassa with a family-friendly garden, and the gateway to Satmaliya Deer Sanctuary and Madhuban Dam.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Khanvel", "Dadra and Nagar Haveli", "Silvassa", "Satmaliya Deer Sanctuary", "Madhuban Dam", "Family Trip"],
    readTime: "10 min",
    featured: false,
  },
  {
    slug: "moti-daman-fort-travel-guide",
    title: "Moti Daman Fort: The Fort of St. Jerome, Bastion by Bastion",
    excerpt:
      "A 16th-century Portuguese fortress so large it doesn't just guard a town — it contains one. Ten bastions, a gilded church, old cannons, and a district collectorate, all inside the same set of walls.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Moti Daman Fort", "Fort of St. Jerome", "Daman", "Daman and Diu", "Bom Jesus Church", "Portuguese Heritage"],
    readTime: "11 min",
    featured: false,
  },
  {
    slug: "nani-daman-travel-guide",
    title: "Nani Daman Travel Guide: Fort, Harbour & Lighthouse",
    excerpt:
      "The smaller, northern quarter of Daman town — a working fishing harbour, the Fort of St. Francis Xavier, and a lighthouse across the river from Moti Daman.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Nani Daman", "Daman", "Daman and Diu", "Fishing Harbour", "Portuguese Heritage"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "satmaliya-deer-sanctuary-travel-guide",
    title: "Satmaliya Deer Sanctuary: Visit Guide & Tips",
    excerpt:
      "A small, quiet forest sanctuary near Khanvel where spotted deer roam close to the trees — how to reach it, what to expect, and how to pair it with Madhuban Dam.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Satmaliya Deer Sanctuary", "Dadra and Nagar Haveli", "Silvassa", "Khanvel", "Wildlife"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "vanganga-lake-garden-travel-guide",
    title: "Vanganga Lake Garden, Daman: Complete Visit Guide",
    excerpt:
      "A landscaped garden built around a lake, dotted with miniature replicas of famous world landmarks — one of Daman's most relaxed, easy-to-love family stops.",
    image: "/images/destinations/goa/hero.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Vanganga Lake Garden", "Daman", "Daman and Diu", "Family Friendly", "Lake Garden", "Photography"],
    readTime: "8 min",
    featured: false,
  },
  {
    slug: "madhuban-dam-travel-guide",
    title: "Madhuban Dam Travel Guide: Reservoir, Viewpoint & Picnic Spot",
    excerpt:
      "A dam on the Damanganga river whose reservoir stretches to Dudhni's boat jetties — the dam viewpoint, forest and birdlife, and a half-day plan near Silvassa.",
    image: "/images/destinations/goa/beach.jpg",
    category: "Off-beat",
    categoryColor: "bg-forest-100 text-forest-700",
    tags: ["Madhuban Dam", "Dadra and Nagar Haveli", "Silvassa", "Dudhni", "Reservoir"],
    readTime: "9 min",
    featured: false,
  },
  {
    slug: "gangeshwar-temple-travel-guide",
    title: "Gangeshwar Temple, Diu: A Shiva Shrine Washed by the Sea",
    excerpt:
      "Five natural rock lingams set among the boulders on Diu's southern coastline, partly covered by the tide — when to go, how to visit respectfully, and how to stay safe.",
    image: "/images/destinations/goa/beach.jpg",
    category: "Heritage",
    categoryColor: "bg-purple-100 text-purple-700",
    tags: ["Gangeshwar Temple", "Diu", "Daman and Diu", "Shiva Temple", "Coastal Shrine", "Pilgrimage"],
    readTime: "9 min",
    featured: false,
  },
];

export const popularTags = [
  "Himachal Pradesh",
  "Ladakh",
  "Uttarakhand",
  "Karnataka",
  "Road Trip",
  "Trekking",
  "Budget Travel",
  "Solo Travel",
  "Adventure",
  "Yoga",
  "Wildlife",
  "Beaches",
  "Heritage",
  "Off-beat",
];

export const readingListItems = [
  {
    slug: "manali-travel-guide",
    title: "Manali Travel Guide",
    readTime: "16 min",
  },
  {
    slug: "spiti-valley-travel-guide",
    title: "Spiti Valley Complete Guide",
    readTime: "22 min",
  },
  {
    slug: "rishikesh-adventure-travel-guide",
    title: "Rishikesh Adventure Guide",
    readTime: "18 min",
  },
  { slug: "coorg-travel-guide", title: "Coorg Travel Guide", readTime: "17 min" },
];
