// Heritage & Cultural Tourism cluster. Lookups over the generated heritage index (scripts/heritage/build.py). Safe to
// import from client components: titles, facets and links only.
import index from "./heritage-index.json";
import type { AdvIndexEntry } from "./adventure-links";
import guideLinks from "./heritage-guide-links.json";

export const heritageIndex = index as AdvIndexEntry[];

const bySlug = new Map(heritageIndex.map((e) => [e.slug, e]));

export function heritageEntry(slug: string) {
  return bySlug.get(slug);
}

export function heritageByKind(kind: AdvIndexEntry["kind"]) {
  return heritageIndex.filter((e) => e.kind === kind);
}

/** Heritage articles sharing a region or tradition with this one, most overlap first. */
export function relatedHeritage(slug: string, n = 6) {
  const me = bySlug.get(slug);
  if (!me) return [];
  const facets = new Set([...me.regions, ...me.activities]);
  return heritageIndex
    .filter((e) => e.slug !== slug)
    .map((e) => ({ e, s: [...e.regions, ...e.activities].filter((f) => facets.has(f)).length + (e.kind === "pillar" ? 0.5 : 0) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, n)
    .map((x) => x.e);
}

// State package pages → heritage articles about that state.
const byPackage: Record<string, string[]> = {
  rajasthan: ["heritage-tourism-in-rajasthan", "forts-of-rajasthan", "amber-fort", "mehrangarh-fort", "rajasthan-heritage-itinerary"],
  gujarat: ["heritage-tourism-in-gujarat", "gujarat-heritage-itinerary", "champaner-pavagadh", "lothal", "rann-utsav"],
  "madhya-pradesh": ["heritage-tourism-in-madhya-pradesh", "madhya-pradesh-heritage-itinerary"],
  maharashtra: ["heritage-tourism-in-maharashtra", "forts-in-maharashtra", "elephanta-caves", "rock-cut-caves-in-india"],
  karnataka: ["heritage-tourism-in-karnataka", "belur-halebidu-hoysala-temples", "deccan-sultanate-heritage", "south-india-heritage-itinerary"],
  "tamil-nadu": ["heritage-tourism-in-tamil-nadu", "south-india-heritage-itinerary", "temple-architecture-of-india"],
  "uttar-pradesh": ["heritage-tourism-in-uttar-pradesh", "taj-mahal", "mughal-monuments-in-india", "golden-triangle-itinerary"],
  delhi: ["heritage-tourism-in-delhi", "red-fort", "qutub-minar", "humayuns-tomb", "golden-triangle-itinerary"],
  odisha: ["heritage-tourism-in-odisha", "handicrafts-of-india"],
  "west-bengal": ["heritage-tourism-in-west-bengal", "mountain-railways-of-india"],
  telangana: ["heritage-tourism-in-telangana", "deccan-sultanate-heritage"],
  kerala: ["heritage-tourism-in-kerala", "classical-dance-and-music-in-india"],
  nagaland: ["hornbill-festival", "tribal-tourism-in-india"],
  goa: ["colonial-heritage-in-india"],
  puducherry: ["colonial-heritage-in-india"],
  "himachal-pradesh": ["mountain-railways-of-india"],
  bihar: ["archaeological-sites-in-india"],
  assam: ["unesco-world-heritage-sites-in-india", "tribal-tourism-in-india"],
  chhattisgarh: ["tribal-tourism-in-india"],
  jharkhand: ["tribal-tourism-in-india"],
  meghalaya: ["tribal-tourism-in-india"],
  "andhra-pradesh": ["rock-cut-caves-in-india"],
};

export function heritageForPackage(packageSlug: string) {
  return (byPackage[packageSlug] ?? []).map((s) => bySlug.get(s)).filter((e): e is AdvIndexEntry => Boolean(e));
}

// Guides that should point readers to a heritage article (GuideTripCTA),
// generated by scripts/heritage/build.py from scripts/heritage/guide-links.json.
export const heritageForGuide = guideLinks as Record<string, { slug: string; label: string }>;
