// Hill Station Travel cluster. Lookups over the generated hills index (scripts/hills/build.py). Safe to
// import from client components: titles, facets and links only.
import index from "./hills-index.json";
import type { AdvIndexEntry } from "./adventure-links";
import guideLinks from "./hills-guide-links.json";

export const hillsIndex = index as AdvIndexEntry[];

const bySlug = new Map(hillsIndex.map((e) => [e.slug, e]));

export function hillsEntry(slug: string) {
  return bySlug.get(slug);
}

/** Hill-station articles sharing a region or activity with this one, most overlap first. */
export function relatedHills(slug: string, n = 6) {
  const me = bySlug.get(slug);
  if (!me) return [];
  const facets = new Set([...me.regions, ...me.activities]);
  return hillsIndex
    .filter((e) => e.slug !== slug)
    .map((e) => ({ e, s: [...e.regions, ...e.activities].filter((f) => facets.has(f)).length + (e.kind === "pillar" ? 0.5 : 0) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, n)
    .map((x) => x.e);
}

// State package pages → hill-station articles about that state.
const byPackage: Record<string, string[]> = {
  "himachal-pradesh": ["hill-stations-in-himachal-pradesh", "shimla-manali-itinerary", "places-to-see-snow-in-india"],
  uttarakhand: ["hill-stations-in-uttarakhand", "uttarakhand-hill-stations-itinerary", "hill-stations-near-delhi"],
  kashmir: ["hill-stations-in-jammu-and-kashmir", "kashmir-itinerary", "places-to-see-snow-in-india"],
  sikkim: ["hill-stations-in-sikkim", "darjeeling-sikkim-itinerary"],
  "west-bengal": ["hill-stations-in-west-bengal", "darjeeling-sikkim-itinerary", "tea-tourism-in-india"],
  meghalaya: ["hill-stations-in-meghalaya", "monsoon-hill-stations-in-india"],
  "arunachal-pradesh": ["hill-stations-in-northeast-india"],
  nagaland: ["hill-stations-in-northeast-india"],
  mizoram: ["hill-stations-in-northeast-india"],
  manipur: ["hill-stations-in-northeast-india"],
  assam: ["hill-stations-in-northeast-india", "tea-tourism-in-india"],
  "tamil-nadu": ["hill-stations-in-tamil-nadu", "south-india-hill-stations-itinerary"],
  kerala: ["hill-stations-in-kerala", "south-india-hill-stations-itinerary", "tea-tourism-in-india"],
  karnataka: ["hill-stations-in-karnataka", "coffee-plantation-tourism-in-india"],
  maharashtra: ["hill-stations-in-maharashtra", "hill-stations-near-mumbai", "monsoon-hill-stations-in-india"],
  gujarat: ["hill-stations-in-western-and-central-india"],
  rajasthan: ["hill-stations-in-western-and-central-india"],
  "madhya-pradesh": ["hill-stations-in-western-and-central-india"],
  "andhra-pradesh": ["hill-stations-in-south-india", "coffee-plantation-tourism-in-india"],
  "leh-ladakh": ["best-mountain-destinations-in-india", "mountain-road-trips-in-india"],
};

export function hillsForPackage(packageSlug: string) {
  return (byPackage[packageSlug] ?? []).map((s) => bySlug.get(s)).filter((e): e is AdvIndexEntry => Boolean(e));
}

// Guides that should point readers to a hill-station article (GuideTripCTA),
// generated by scripts/hills/build.py from scripts/hills/guide-links.json.
export const hillsForGuide = guideLinks as Record<string, { slug: string; label: string }>;
