// Nature Travel cluster. Lookups over the generated nature index (scripts/nature/build.py). Safe to
// import from client components: titles, facets and links only.
import index from "./nature-index.json";
import type { AdvIndexEntry } from "./adventure-links";
import guideLinks from "./nature-guide-links.json";

export const natureIndex = index as AdvIndexEntry[];

const bySlug = new Map(natureIndex.map((e) => [e.slug, e]));

export function natureEntry(slug: string) {
  return bySlug.get(slug);
}

/** Nature articles sharing a region or activity with this one, most overlap first. */
export function relatedNature(slug: string, n = 6) {
  const me = bySlug.get(slug);
  if (!me) return [];
  const facets = new Set([...me.regions, ...me.activities]);
  return natureIndex
    .filter((e) => e.slug !== slug)
    .map((e) => ({ e, s: [...e.regions, ...e.activities].filter((f) => facets.has(f)).length + (e.kind === "pillar" ? 0.5 : 0) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, n)
    .map((x) => x.e);
}

// State package pages → nature articles about that state.
const byPackage: Record<string, string[]> = {
  kerala: ["nature-travel-in-kerala", "kerala-nature-itinerary", "western-ghats-nature-travel", "waterfalls-in-india"],
  karnataka: ["nature-travel-in-karnataka", "western-ghats-nature-itinerary", "waterfalls-in-india"],
  meghalaya: ["nature-travel-in-meghalaya", "meghalaya-nature-itinerary", "natural-caves-in-india"],
  uttarakhand: ["nature-travel-in-uttarakhand", "flower-valleys-and-blooms-in-india", "himalayan-nature-travel"],
  "himachal-pradesh": ["nature-travel-in-himachal-pradesh", "valleys-in-india", "himalayan-nature-travel"],
  odisha: ["nature-travel-in-odisha", "lakes-in-india"],
  "madhya-pradesh": ["nature-travel-in-madhya-pradesh", "natural-wonders-of-india"],
  goa: ["western-ghats-nature-travel", "waterfalls-in-india"],
  maharashtra: ["western-ghats-nature-travel", "flower-valleys-and-blooms-in-india"],
  "tamil-nadu": ["western-ghats-nature-travel", "forest-destinations-in-india"],
  sikkim: ["nature-travel-in-northeast-india", "flower-valleys-and-blooms-in-india", "lakes-in-india"],
  "arunachal-pradesh": ["nature-travel-in-northeast-india", "valleys-in-india"],
  assam: ["nature-travel-in-northeast-india", "riverside-destinations-in-india"],
  nagaland: ["nature-travel-in-northeast-india", "village-tourism-in-india"],
  manipur: ["nature-travel-in-northeast-india", "lakes-in-india"],
  mizoram: ["nature-travel-in-northeast-india"],
  tripura: ["nature-travel-in-northeast-india"],
  kashmir: ["himalayan-nature-travel", "valleys-in-india", "lakes-in-india"],
  "leh-ladakh": ["himalayan-nature-travel", "lakes-in-india"],
  "andhra-pradesh": ["natural-caves-in-india", "natural-wonders-of-india"],
  chhattisgarh: ["natural-caves-in-india", "waterfalls-in-india"],
  gujarat: ["natural-wonders-of-india"],
  "andaman-nicobar": ["biodiversity-hotspots-in-india", "natural-wonders-of-india"],
};

export function natureForPackage(packageSlug: string) {
  return (byPackage[packageSlug] ?? []).map((s) => bySlug.get(s)).filter((e): e is AdvIndexEntry => Boolean(e));
}

// Guides that should point readers to a nature article (GuideTripCTA),
// generated by scripts/nature/build.py from scripts/nature/guide-links.json.
export const natureForGuide = guideLinks as Record<string, { slug: string; label: string }>;
