// Road Trips cluster. Lookups over the generated roadtrips index (scripts/roadtrips/build.py). Safe to
// import from client components: titles, facets and links only.
import index from "./roadtrips-index.json";
import type { AdvIndexEntry } from "./adventure-links";
import guideLinks from "./roadtrips-guide-links.json";

export const roadtripsIndex = index as AdvIndexEntry[];

const bySlug = new Map(roadtripsIndex.map((e) => [e.slug, e]));

export function roadtripsEntry(slug: string) {
  return bySlug.get(slug);
}

/** Roadtrips articles sharing a region or activity with this one, most overlap first. */
export function relatedRoadtrips(slug: string, n = 6) {
  const me = bySlug.get(slug);
  if (!me) return [];
  const facets = new Set([...me.regions, ...me.activities]);
  return roadtripsIndex
    .filter((e) => e.slug !== slug)
    .map((e) => ({ e, s: [...e.regions, ...e.activities].filter((f) => facets.has(f)).length + (e.kind === "pillar" ? 0.5 : 0) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, n)
    .map((x) => x.e);
}

// State package pages → roadtrips articles about that state.
const byPackage: Record<string, string[]> = {
  "himachal-pradesh": ["road-trips-in-himachal-pradesh", "delhi-to-manali-road-trip", "spiti-valley-road-trip", "delhi-to-shimla-road-trip"],
  uttarakhand: ["road-trips-in-uttarakhand", "delhi-to-rishikesh-road-trip"],
  "leh-ladakh": ["manali-to-leh-road-trip", "srinagar-to-leh-road-trip"],
  kashmir: ["srinagar-to-leh-road-trip"],
  rajasthan: ["rajasthan-road-trip", "winter-road-trips-in-india"],
  kerala: ["kerala-road-trip", "kochi-to-munnar-road-trip", "coastal-road-trips-in-india"],
  karnataka: ["bengaluru-to-coorg-road-trip", "road-trips-from-bengaluru", "western-ghats-road-trips", "bengaluru-to-goa-road-trip"],
  "tamil-nadu": ["bengaluru-to-ooty-road-trip", "chennai-to-pondicherry-road-trip", "road-trips-from-chennai"],
  puducherry: ["chennai-to-pondicherry-road-trip"],
  goa: ["mumbai-to-goa-road-trip", "bengaluru-to-goa-road-trip"],
  maharashtra: ["road-trips-from-mumbai", "mumbai-to-goa-road-trip", "western-ghats-road-trips"],
  telangana: ["road-trips-from-hyderabad"],
  "andhra-pradesh": ["road-trips-from-hyderabad"],
  "west-bengal": ["road-trips-from-kolkata"],
  "arunachal-pradesh": ["guwahati-to-tawang-road-trip", "northeast-india-road-trips"],
  assam: ["northeast-india-road-trips", "guwahati-to-tawang-road-trip"],
  meghalaya: ["northeast-india-road-trips"],
  sikkim: ["northeast-india-road-trips"],
  gujarat: ["winter-road-trips-in-india", "coastal-road-trips-in-india"],
  odisha: ["coastal-road-trips-in-india"],
  "madhya-pradesh": ["wildlife-road-trips-in-india"],
  delhi: ["road-trips-from-delhi"],
};

export function roadtripsForPackage(packageSlug: string) {
  return (byPackage[packageSlug] ?? []).map((s) => bySlug.get(s)).filter((e): e is AdvIndexEntry => Boolean(e));
}

// Guides that should point readers to a roadtrips article (GuideTripCTA),
// generated by scripts/roadtrips/build.py from scripts/roadtrips/guide-links.json.
export const roadtripsForGuide = guideLinks as Record<string, { slug: string; label: string }>;
