// Spiritual Tourism cluster. Lookups over the generated spiritual index (scripts/spiritual/build.py). Safe to
// import from client components: titles, facets and links only.
import index from "./spiritual-index.json";
import type { AdvIndexEntry } from "./adventure-links";
import guideLinks from "./spiritual-guide-links.json";

export const spiritualIndex = index as AdvIndexEntry[];

const bySlug = new Map(spiritualIndex.map((e) => [e.slug, e]));

export function spiritualEntry(slug: string) {
  return bySlug.get(slug);
}

export function spiritualByKind(kind: AdvIndexEntry["kind"]) {
  return spiritualIndex.filter((e) => e.kind === kind);
}

/** Spiritual articles sharing a region or tradition with this one, most overlap first. */
export function relatedSpiritual(slug: string, n = 6) {
  const me = bySlug.get(slug);
  if (!me) return [];
  const facets = new Set([...me.regions, ...me.activities]);
  return spiritualIndex
    .filter((e) => e.slug !== slug)
    .map((e) => ({ e, s: [...e.regions, ...e.activities].filter((f) => facets.has(f)).length + (e.kind === "pillar" ? 0.5 : 0) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, n)
    .map((x) => x.e);
}

// State package pages → spiritual articles about that state.
const byPackage: Record<string, string[]> = {
  "uttar-pradesh": ["spiritual-tourism-in-uttar-pradesh", "ayodhya-varanasi-prayagraj-tour", "buddhist-circuit-in-india"],
  uttarakhand: ["spiritual-tourism-in-uttarakhand", "char-dham-yatra-guide", "kedarnath-badrinath-yatra", "hemkund-sahib-yatra", "yoga-in-rishikesh"],
  gujarat: ["spiritual-tourism-in-gujarat", "nageshwar-jyotirlinga", "char-dham-of-india", "jain-pilgrimage-in-india"],
  rajasthan: ["spiritual-tourism-in-rajasthan", "ranakpur-jain-temple", "sufi-shrines-in-india"],
  maharashtra: ["spiritual-tourism-in-maharashtra", "jyotirlingas-in-maharashtra", "trimbakeshwar-jyotirlinga", "bhimashankar-jyotirlinga", "grishneshwar-jyotirlinga", "pilgrimage-trips-from-mumbai"],
  "madhya-pradesh": ["spiritual-tourism-in-madhya-pradesh", "12-jyotirlingas-in-india", "kumbh-mela"],
  "tamil-nadu": ["spiritual-tourism-in-tamil-nadu", "famous-temples-in-india", "char-dham-of-india"],
  karnataka: ["spiritual-tourism-in-karnataka", "shravanabelagola-gommateshwara"],
  kerala: ["spiritual-tourism-in-kerala", "famous-temples-in-india"],
  "andhra-pradesh": ["spiritual-tourism-in-andhra-pradesh", "12-jyotirlingas-in-india"],
  telangana: ["famous-temples-in-india"],
  odisha: ["spiritual-tourism-in-odisha", "char-dham-of-india", "spiritual-festivals-in-india"],
  "west-bengal": ["spiritual-tourism-in-west-bengal", "shakti-peethas-in-india"],
  bihar: ["spiritual-tourism-in-bihar", "buddhist-circuit-in-india", "panj-takht-yatra"],
  "himachal-pradesh": ["spiritual-tourism-in-himachal-pradesh", "buddhist-tourism-in-india"],
  kashmir: ["spiritual-tourism-in-jammu-and-kashmir", "sufi-shrines-in-india"],
  punjab: ["sikh-pilgrimage-in-india", "panj-takht-yatra"],
  delhi: ["pilgrimage-trips-from-delhi", "sufi-shrines-in-india"],
  jharkhand: ["jain-pilgrimage-in-india", "12-jyotirlingas-in-india"],
  assam: ["shakti-peethas-in-india"],
  sikkim: ["buddhist-tourism-in-india"],
  "leh-ladakh": ["buddhist-tourism-in-india"],
  "arunachal-pradesh": ["buddhist-tourism-in-india"],
};

export function spiritualForPackage(packageSlug: string) {
  return (byPackage[packageSlug] ?? []).map((s) => bySlug.get(s)).filter((e): e is AdvIndexEntry => Boolean(e));
}

// Guides that should point readers to a spiritual article (GuideTripCTA),
// generated by scripts/spiritual/build.py from scripts/spiritual/guide-links.json.
export const spiritualForGuide = guideLinks as Record<string, { slug: string; label: string }>;
