// Wildlife Tourism cluster. Lookups over the generated wildlife index (scripts/wildlife/build.py). Safe to
// import from client components: titles, facets and links only.
import index from "./wildlife-index.json";
import type { AdvIndexEntry } from "./adventure-links";
import guideLinks from "./wildlife-guide-links.json";

export const wildlifeIndex = index as AdvIndexEntry[];

const bySlug = new Map(wildlifeIndex.map((e) => [e.slug, e]));

export function wildlifeEntry(slug: string) {
  return bySlug.get(slug);
}

export function wildlifeByKind(kind: AdvIndexEntry["kind"]) {
  return wildlifeIndex.filter((e) => e.kind === kind);
}

/** Wildlife articles sharing a region or activity with this one, most overlap first. */
export function relatedWildlife(slug: string, n = 6) {
  const me = bySlug.get(slug);
  if (!me) return [];
  const facets = new Set([...me.regions, ...me.activities]);
  return wildlifeIndex
    .filter((e) => e.slug !== slug)
    .map((e) => ({ e, s: [...e.regions, ...e.activities].filter((f) => facets.has(f)).length + (e.kind === "pillar" ? 0.5 : 0) }))
    .filter((x) => x.s > 0)
    .sort((a, b) => b.s - a.s)
    .slice(0, n)
    .map((x) => x.e);
}

// State package pages → wildlife articles about that state.
const byPackage: Record<string, string[]> = {
  rajasthan: ["wildlife-tourism-in-rajasthan", "sariska-tiger-reserve", "leopard-safari-in-india"],
  "madhya-pradesh": ["wildlife-tourism-in-madhya-pradesh", "pench-tiger-reserve", "satpura-tiger-reserve", "tiger-safari-in-india"],
  uttarakhand: ["wildlife-tourism-in-uttarakhand", "tiger-safari-in-india"],
  maharashtra: ["wildlife-tourism-in-maharashtra", "tiger-safari-in-india"],
  karnataka: ["wildlife-tourism-in-karnataka", "leopard-safari-in-india"],
  kerala: ["wildlife-tourism-in-kerala", "birdwatching-in-india"],
  assam: ["wildlife-tourism-in-assam", "where-to-see-rhinos-in-india"],
  gujarat: ["wildlife-tourism-in-gujarat", "where-to-see-wildlife-in-india"],
  "west-bengal": ["wildlife-tourism-in-west-bengal", "where-to-see-rhinos-in-india"],
  odisha: ["wildlife-tourism-in-odisha", "birdwatching-in-india"],
  "tamil-nadu": ["wildlife-tourism-in-tamil-nadu"],
  "leh-ladakh": ["snow-leopard-tours-in-india"],
  "himachal-pradesh": ["snow-leopard-tours-in-india"],
  "uttar-pradesh": ["best-tiger-reserves-in-india", "where-to-see-rhinos-in-india"],
  haryana: ["birdwatching-in-india"],
  goa: ["best-wildlife-sanctuaries-in-india"],
  "andhra-pradesh": ["best-tiger-reserves-in-india"],
  telangana: ["best-tiger-reserves-in-india"],
  chhattisgarh: ["best-tiger-reserves-in-india"],
  jharkhand: ["best-tiger-reserves-in-india"],
  "arunachal-pradesh": ["best-national-parks-in-india", "birdwatching-in-india"],
  delhi: ["birdwatching-in-india"],
};

export function wildlifeForPackage(packageSlug: string) {
  return (byPackage[packageSlug] ?? []).map((s) => bySlug.get(s)).filter((e): e is AdvIndexEntry => Boolean(e));
}

// Guides that should point readers to a wildlife article (GuideTripCTA),
// generated by scripts/wildlife/build.py from scripts/wildlife/guide-links.json.
export const wildlifeForGuide = guideLinks as Record<string, { slug: string; label: string }>;
