"""Generate the image-audit documentation from the pipeline data.

docs/blog-image-audit.md         inventory: every guide, before -> after
docs/blog-image-progress.md      progress tracker
docs/image-sources.md            provenance for every newly sourced image
docs/blog-image-manual-review.md places with no verifiable image, open issues
"""
import collections, glob, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
DOCS = os.path.join(ROOT, "docs")
SITE = "https://club.kudozz.in/blog/"

before = {b["slug"]: b for b in json.load(open(os.path.join(HERE, "inventory-before.json")))}
after = {b["slug"]: b for b in json.load(open(os.path.join(HERE, "inventory.json")))}
plan = {p["slug"]: p for p in json.load(open(os.path.join(HERE, "plan.json")))}
from store import load_resolved  # noqa: E402
res = load_resolved()
applied = json.load(open(os.path.join(HERE, "applied.json"))) if os.path.exists(os.path.join(HERE, "applied.json")) else {}
rejects = set(json.load(open(os.path.join(HERE, "rejects.json"))))
reviewed = set(json.load(open(os.path.join(HERE, "reviewed.json"))))
cred = json.load(open(os.path.join(ROOT, "public/images/blogs/IMAGE_CREDITS.json")))["images"]
credited = {"/images/" + c["path"] for c in cred}


def md(s):
    return (s or "").replace("|", "\\|").replace("\n", " ")


def counts(b):
    imgs = [i for i in b["images"] if i["kind"] != "data"]
    hero = next((i for i in imgs if i["kind"] == "hero"), None)
    return {
        "hero": hero["src"] if hero else "",
        "hero_ok": bool(hero and hero["src"] in credited),
        "content": sum(1 for i in imgs if i["kind"] == "content"),
        "uncredited": sum(1 for i in imgs if i["src"] not in credited),
        "hedged": sum(1 for i in imgs if i["hedged"]),
    }


# ---------------------------------------------------------------- audit
def srcset(b, kind=None):
    return [i["src"] for i in b["images"] if i["kind"] != "data" and (kind is None or i["kind"] == kind)]


# Totals computed from the before/after inventories (ground truth), not from apply counters.
T = collections.Counter()
for slug, b0 in before.items():
    b1 = after[slug]
    h0, h1 = srcset(b0, "hero")[0], srcset(b1, "hero")[0]
    T["hero_replaced" if h0 != h1 else "hero_kept"] += 1
    c0, c1 = srcset(b0, "content"), srcset(b1, "content")
    T["content_kept"] += sum(1 for s in c0 if s in c1)
    T["content_removed"] += sum(1 for s in c0 if s not in c1)
    T["content_new"] += sum(1 for s in c1 if s not in c0)
    T["broken_before"] += sum(1 for i in b0["images"] if not i["exists"] and not i["src"].startswith("{"))
    T["broken_after"] += sum(1 for i in b1["images"] if not i["exists"] and not i["src"].startswith("{"))
rows, total = [], collections.Counter()
for slug in sorted(before):
    b0, b1, p = before[slug], after.get(slug, before[slug]), plan[slug]
    c0, c1 = counts(b0), counts(b1)

    rows.append(
        f"| [{md(b0['title'][:60])}]({SITE}{slug}) | {md(b0['state'])} | {md(p['place'])} | "
        f"{c0['content']} → {c1['content']} | {c0['uncredited']} → {c1['uncredited']} | {c0['hedged']} → {c1['hedged']} | "
        f"{'yes' if c1['hero_ok'] else 'NO'} | {len(p['named'])} |")

open(os.path.join(DOCS, "blog-image-audit.md"), "w").write(f"""# Blog Image Audit

Generated by `scripts/image-audit/report.py` from the pipeline data. Every guide in `src/app/blog/*/page.tsx` ({len(before)} guides) is listed.

## How images work in this codebase

- **Framework:** Next.js 14 App Router. Each guide is a hand-written `src/app/blog/<slug>/page.tsx`; there is no CMS/MDX. Card images for listings come from `src/lib/blog-posts.ts`.
- **Rendering:** `next/image` everywhere (`fill` inside fixed-height containers, so no layout shift). Optimised to AVIF/WebP at request time (`next.config.js`).
- **Hero image** appears in 4 places per guide, all updated together: the hero `<Image>`, OpenGraph `images[].url` (+ `alt`, `width`, `height`), Twitter `images`, and the JSON-LD `BlogPosting.image`, plus the card image in `blog-posts.ts`.
- **Content images:** `<Image>` inside `div.h-72` wrappers under headings; new ones use `GuideFigure` / `GuidePhotoRow` (`src/components/ui/GuideImages.tsx`).
- **Storage:** `public/images/blogs/<state>/<guide>/<place>-<guide-place>.webp`. Provenance for every file in `public/images/blogs/IMAGE_CREDITS.json`, shown publicly at `/image-credits`.

## Totals

| | Count |
|---|---|
| Guides audited | {len(before)} |
| Heroes kept (verified correct place) or kept for lack of a verified alternative | {T['hero_kept']} |
| Heroes replaced with a verified image of the place | {T['hero_replaced']} |
| Content images kept | {T['content_kept']} |
| Content images removed (wrong place, generic stand-in, duplicate of hero, or redundant) | {T['content_removed']} |
| New verified content images placed | {T['content_new']} |
| Content images before → after | {sum(len(srcset(b, 'content')) for b in before.values())} → {sum(len(srcset(b, 'content')) for b in after.values())} |

## Per-guide inventory

Columns: content images before → after · images without provenance before → after · hedged alt text ("evoking…", "representative of…") before → after · hero verified · specific places identified in the article.

| Guide | State/UT | Primary place | Content imgs | Unprovenanced | Hedged alt | Hero verified | Places named |
|---|---|---|---|---|---|---|---|
""" + "\n".join(rows) + "\n")

# ---------------------------------------------------------------- progress
done = [s for s in before if s in applied]
prow = []
for slug in sorted(before):
    b0, b1 = before[slug], after[slug]
    c0, c1 = srcset(b0, "content"), srcset(b1, "content")
    status = "COMPLETE" if slug in applied else "PENDING"
    prow.append(f"| {md(b0['title'][:55])} | /blog/{slug} | "
                f"{'replaced' if srcset(b0, 'hero') != srcset(b1, 'hero') else 'kept'} | {len(c1)} | "
                f"{sum(1 for s in c0 if s not in c1)} removed | {sum(1 for s in c1 if s not in c0)} | {status} |")
open(os.path.join(DOCS, "blog-image-progress.md"), "w").write(f"""# Blog Image Progress

Total blogs: {len(before)}

Completed: {len(done)}
In progress: 0
Remaining: {len(before) - len(done)}

Images reviewed visually: {len(reviewed)} (rejected and re-sourced: {len(rejects)})

| Blog | URL | Hero | Content Images | Replacements | New Images | Status |
|---|---|---|---|---|---|---|
""" + "\n".join(prow) + "\n")

# ---------------------------------------------------------------- sources
new = [c for c in cred if c.get("accessed")]
srows = [f"| `{c['path'].split('/')[-1]}` | {', '.join(md(u) for u in c['usedIn'])} | {md(c.get('location'))} | "
         f"[{md(c['originalFile'][:50])}]({c['sourcePage']}) | {md(c['author'][:40])} | {c['license']} | "
         f"{'Required' if c['license'] not in ('CC0', 'Public domain') else 'Not required'} | {c['accessed']} |"
         for c in sorted(new, key=lambda c: c["path"])]
open(os.path.join(DOCS, "image-sources.md"), "w").write(f"""# Image Sources

Every image sourced in the 2026-09 blog image audit ({len(new)} files). All from **Wikimedia Commons**, restricted to licences that allow commercial reuse (CC0, Public domain, CC BY, CC BY-SA). Licence, author and source page were read from the Commons API (`extmetadata`) at download time, not typed by hand. The full machine-readable record (including {len(cred) - len(new)} images credited before this audit) is `public/images/blogs/IMAGE_CREDITS.json`; attribution is displayed publicly at [/image-credits](https://club.kudozz.in/image-credits).

CC BY / CC BY-SA require attribution (satisfied by `/image-credits`). CC BY-SA images were resized and converted to WebP; those derivatives remain under the same licence.

| Filename | Used in | Location | Original | Creator | Licence | Attribution | Accessed |
|---|---|---|---|---|---|---|---|
""" + "\n".join(srows) + "\n")

# ---------------------------------------------------------------- manual review
heroes, optional = [], collections.defaultdict(list)
for slug in sorted(after):
    b1, p = after[slug], plan[slug]
    h = srcset(b1, "hero")[0]
    if h not in credited:
        hi = next(i for i in b1["images"] if i["kind"] == "hero")
        status = "Stand-in: a different place" if hi["hedged"] else "Appears to show the place; source/licence unknown"
        heroes.append(f"| [/blog/{slug}]({SITE}{slug}) | {md(p['place'])} | {status} | `{h}` | {md(hi['alt'])[:90]} | "
                      f"Commons searched for \"{md(p['place'])}\" (+ state, panorama/view variants): no free-licence landscape "
                      f"photo that names the place and passed visual review | Supply an original or licensed photo of {md(p['place'])} |")
    r = res.get(slug, {"slots": {}})
    for si, s in enumerate(p["slots"]):
        if s["type"] not in ("add-h3", "add-row"):
            continue
        keys = [f"{si}"] if s["type"] == "add-h3" else [f"{si}.{k}" for k in range(len(s["places"]))]
        for k in keys:
            v = r["slots"].get(k)
            if v and v.get("src") and f"{slug}:{k}|{v['title']}" not in rejects and v["src"] in " ".join(srcset(b1)):
                continue
            place = s["places"][int(k.split(".")[1])] if "." in k else s["places"][0]
            optional[slug].append(place)
still = collections.Counter(i["src"] for b in after.values() for i in b["images"]
                            if i["kind"] != "data" and i["src"] not in credited and not i["src"].startswith("{"))
opt_rows = [f"| /blog/{s} | {md(', '.join(v))} |" for s, v in sorted(optional.items())]
open(os.path.join(DOCS, "blog-image-manual-review.md"), "w").write(f"""# Blog Image Manual Review

Everything the audit could not resolve with a verifiable, correctly located image. **No unrelated image was inserted to fill a gap**; where no verified image existed, the section was left without one.

## 1. Heroes without a verified photo ({len(heroes)} guides) — highest priority

These guides kept their previous hero because every page needs one and no verified replacement existed. **Stand-ins** show somewhere else (the alt text says so honestly, e.g. "evoking…"): replace them. The others appear to show the right place but have no source/licence record: confirm provenance or replace.

| Guide | Place | Status | Current hero | Current alt text | What was searched | Recommended action |
|---|---|---|---|---|---|---|
""" + "\n".join(heroes) + f"""

## 2. Image files in use without a provenance record ({len(still)})

All are pre-audit files under `/images/destinations/` (plus a few older `/images/blogs/` files) used as heroes above. Confirm their source and licence (e.g. Unsplash/Pexels licence, purchase receipt, own photo) and add them to `public/images/blogs/IMAGE_CREDITS.json`, or replace them.

| Image | Guides using it as hero |
|---|---|
""" + "\n".join(f"| `{s}` | {n} |" for s, n in still.most_common()) + f"""

## 3. Named places without a section image ({sum(len(v) for v in optional.values())} places in {len(optional)} guides) — optional

The article names these places under their own heading or list item, but no free-licence photo that clearly shows the named place passed review (typical causes: no Commons coverage, only portrait/low-resolution/detail shots, or only images of a different place with the same name). Adding photos here is optional; the sections read fine without them.

| Guide | Places |
|---|---|
""" + "\n".join(opt_rows) + "\n")
print("docs written:", len(before), "guides,", len(new), "new images,", len(heroes), "heroes +", len(optional), "guides with optional gaps")
