"""Eligibility decisions for every guide. Writes scripts/things-to-do/plan.json.
Tier A = major destination (deep article); B = secondary destination (focused article).
Slugs use the most-searched spelling of the place name (e.g. 'mysore', 'bangalore')."""
import json, os, re
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
inv = json.load(open(os.path.join(ROOT, "scripts/things-to-do/inventory.json")))

# guide-slug-prefix : (slug-suffix, display name, tier, destination type)
E = {
 "andaman-islands": ("andaman", "Andaman Islands", "A", "island region"),
 "havelock-island-andaman": ("havelock-island", "Havelock Island (Swaraj Dweep)", "B", "island"),
 "neil-island-andaman": ("neil-island", "Neil Island (Shaheed Dweep)", "B", "island"),
 "port-blair-andaman": ("port-blair", "Port Blair (Sri Vijaya Puram)", "B", "city"),
 "visakhapatnam": ("vizag", "Visakhapatnam (Vizag)", "B", "coastal city"),
 "araku-valley": ("araku-valley", "Araku Valley", "B", "hill station"),
 "tirupati": ("tirupati", "Tirupati", "B", "pilgrimage town"),
 "tawang": ("tawang", "Tawang", "B", "mountain town"),
 "ziro-valley-arunachal": ("ziro", "Ziro", "B", "valley"),
 "guwahati": ("guwahati", "Guwahati", "B", "city"),
 "kaziranga": ("kaziranga", "Kaziranga", "B", "national park"),
 "majuli": ("majuli", "Majuli", "B", "river island"),
 "bodh-gaya": ("bodh-gaya", "Bodh Gaya", "B", "pilgrimage town"),
 "patna": ("patna", "Patna", "B", "city"),
 "rajgir": ("rajgir", "Rajgir", "B", "heritage town"),
 "chandigarh": ("chandigarh", "Chandigarh", "A", "city"),
 "diu": ("diu", "Diu", "B", "coastal town"),
 "daman": ("daman", "Daman", "B", "coastal town"),
 "delhi": ("delhi", "Delhi", "A", "city"),
 "old-delhi": ("old-delhi", "Old Delhi", "B", "historic district"),
 "goa-beaches": ("goa", "Goa", "A", "beach destination"),
 "ahmedabad": ("ahmedabad", "Ahmedabad", "A", "city"),
 "rann-of-kutch": ("kutch", "Kutch", "B", "desert region"),
 "vadodara": ("vadodara", "Vadodara", "B", "city"),
 "dwarka": ("dwarka", "Dwarka", "B", "pilgrimage town"),
 "saputara": ("saputara", "Saputara", "B", "hill station"),
 "surat": ("surat", "Surat", "B", "city"),
 "gurugram": ("gurgaon", "Gurugram (Gurgaon)", "B", "city"),
 "manali": ("manali", "Manali", "A", "hill station"),
 "shimla": ("shimla", "Shimla", "A", "hill station"),
 "dharamshala": ("dharamshala", "Dharamshala and McLeod Ganj", "A", "hill town"),
 "kasol-kheerganga-trek": ("kasol", "Kasol", "B", "mountain village"),
 "dalhousie": ("dalhousie", "Dalhousie", "B", "hill station"),
 "spiti-valley": ("spiti-valley", "Spiti Valley", "A", "mountain desert valley"),
 "bir-billing": ("bir-billing", "Bir Billing", "B", "adventure destination"),
 "kasauli": ("kasauli", "Kasauli", "B", "hill station"),
 "tirthan-valley": ("tirthan-valley", "Tirthan Valley", "B", "valley"),
 "jammu-kashmir": ("kashmir", "Kashmir", "A", "region"),
 "srinagar": ("srinagar", "Srinagar", "A", "city"),
 "gulmarg": ("gulmarg", "Gulmarg", "B", "hill station"),
 "pahalgam": ("pahalgam", "Pahalgam", "B", "hill station"),
 "sonamarg": ("sonamarg", "Sonamarg", "B", "mountain destination"),
 "jammu": ("jammu", "Jammu", "B", "city"),
 "patnitop": ("patnitop", "Patnitop", "B", "hill station"),
 "ranchi": ("ranchi", "Ranchi", "B", "city"),
 "bengaluru": ("bangalore", "Bengaluru (Bangalore)", "A", "city"),
 "mysuru": ("mysore", "Mysuru (Mysore)", "A", "heritage city"),
 "coorg": ("coorg", "Coorg", "A", "hill region"),
 "hampi": ("hampi", "Hampi", "A", "heritage destination"),
 "chikmagalur": ("chikmagalur", "Chikmagalur", "B", "hill station"),
 "gokarna-beaches": ("gokarna", "Gokarna", "B", "beach destination"),
 "mangaluru": ("mangalore", "Mangaluru (Mangalore)", "B", "coastal city"),
 "udupi": ("udupi", "Udupi", "B", "temple town"),
 "kerala-backwaters": ("kerala", "Kerala", "A", "state"),
 "kochi": ("kochi", "Kochi", "A", "coastal city"),
 "munnar": ("munnar", "Munnar", "A", "hill station"),
 "alappuzha": ("alleppey", "Alappuzha (Alleppey)", "A", "backwater destination"),
 "thekkady": ("thekkady", "Thekkady", "B", "wildlife destination"),
 "wayanad": ("wayanad", "Wayanad", "B", "hill region"),
 "varkala": ("varkala", "Varkala", "B", "beach town"),
 "kovalam": ("kovalam", "Kovalam", "B", "beach town"),
 "kumarakom": ("kumarakom", "Kumarakom", "B", "backwater destination"),
 "leh-ladakh-road-trip": ("ladakh", "Ladakh", "A", "region"),
 "leh": ("leh", "Leh", "A", "mountain town"),
 "nubra-valley": ("nubra-valley", "Nubra Valley", "B", "valley"),
 "lakshadweep-island": ("lakshadweep", "Lakshadweep", "B", "island territory"),
 "bhopal": ("bhopal", "Bhopal", "B", "city"),
 "indore": ("indore", "Indore", "B", "city"),
 "gwalior": ("gwalior", "Gwalior", "B", "heritage city"),
 "khajuraho": ("khajuraho", "Khajuraho", "B", "heritage town"),
 "ujjain": ("ujjain", "Ujjain", "B", "pilgrimage city"),
 "orchha": ("orchha", "Orchha", "B", "heritage town"),
 "pachmarhi": ("pachmarhi", "Pachmarhi", "B", "hill station"),
 "jabalpur": ("jabalpur", "Jabalpur", "B", "city"),
 "mandu": ("mandu", "Mandu", "B", "heritage town"),
 "mumbai": ("mumbai", "Mumbai", "A", "city"),
 "pune": ("pune", "Pune", "A", "city"),
 "lonavala": ("lonavala", "Lonavala", "B", "hill station"),
 "mahabaleshwar": ("mahabaleshwar", "Mahabaleshwar", "B", "hill station"),
 "nashik": ("nashik", "Nashik", "B", "city"),
 "chhatrapati-sambhajinagar": ("aurangabad", "Chhatrapati Sambhajinagar (Aurangabad)", "B", "heritage city"),
 "alibaug": ("alibaug", "Alibaug", "B", "beach town"),
 "matheran": ("matheran", "Matheran", "B", "hill station"),
 "kolhapur": ("kolhapur", "Kolhapur", "B", "city"),
 "imphal": ("imphal", "Imphal", "B", "city"),
 "meghalaya": ("meghalaya", "Meghalaya", "A", "state"),
 "shillong": ("shillong", "Shillong", "A", "hill city"),
 "cherrapunji": ("cherrapunji", "Cherrapunji (Sohra)", "B", "hill destination"),
 "aizawl": ("aizawl", "Aizawl", "B", "hill city"),
 "kohima": ("kohima", "Kohima", "B", "hill city"),
 "bhubaneswar": ("bhubaneswar", "Bhubaneswar", "B", "city"),
 "puri": ("puri", "Puri", "B", "pilgrimage and beach town"),
 "puducherry-district": ("pondicherry", "Puducherry (Pondicherry)", "A", "coastal town"),
 "amritsar": ("amritsar", "Amritsar", "A", "city"),
 "patiala": ("patiala", "Patiala", "B", "heritage city"),
 "jaipur": ("jaipur", "Jaipur", "A", "city"),
 "udaipur-city-of-lakes": ("udaipur", "Udaipur", "A", "city"),
 "jodhpur": ("jodhpur", "Jodhpur", "A", "city"),
 "rajasthan-desert": ("jaisalmer", "Jaisalmer", "A", "desert city"),
 "pushkar": ("pushkar", "Pushkar", "B", "pilgrimage town"),
 "ajmer": ("ajmer", "Ajmer", "B", "pilgrimage city"),
 "bikaner": ("bikaner", "Bikaner", "B", "desert city"),
 "mount-abu": ("mount-abu", "Mount Abu", "B", "hill station"),
 "chittorgarh": ("chittorgarh", "Chittorgarh", "B", "heritage town"),
 "bundi": ("bundi", "Bundi", "B", "heritage town"),
 "sikkim": ("sikkim", "Sikkim", "A", "state"),
 "gangtok": ("gangtok", "Gangtok", "A", "hill city"),
 "pelling": ("pelling", "Pelling", "B", "hill town"),
 "chennai": ("chennai", "Chennai", "A", "city"),
 "madurai": ("madurai", "Madurai", "A", "temple city"),
 "ooty": ("ooty", "Ooty", "A", "hill station"),
 "kodaikanal": ("kodaikanal", "Kodaikanal", "B", "hill station"),
 "mahabalipuram": ("mahabalipuram", "Mahabalipuram", "B", "heritage coastal town"),
 "kanyakumari": ("kanyakumari", "Kanyakumari", "B", "coastal town"),
 "rameswaram": ("rameswaram", "Rameswaram", "B", "pilgrimage island town"),
 "coimbatore": ("coimbatore", "Coimbatore", "B", "city"),
 "thanjavur": ("thanjavur", "Thanjavur", "B", "heritage city"),
 "yercaud": ("yercaud", "Yercaud", "B", "hill station"),
 "hyderabad": ("hyderabad", "Hyderabad", "A", "city"),
 "warangal": ("warangal", "Warangal", "B", "heritage city"),
 "agartala": ("agartala", "Agartala", "B", "city"),
 "agra": ("agra", "Agra", "A", "heritage city"),
 "varanasi": ("varanasi", "Varanasi", "A", "pilgrimage city"),
 "lucknow": ("lucknow", "Lucknow", "A", "city"),
 "mathura": ("mathura", "Mathura", "B", "pilgrimage city"),
 "vrindavan": ("vrindavan", "Vrindavan", "B", "pilgrimage town"),
 "ayodhya": ("ayodhya", "Ayodhya", "B", "pilgrimage city"),
 "prayagraj": ("prayagraj", "Prayagraj", "B", "city"),
 "rishikesh-adventure": ("rishikesh", "Rishikesh", "A", "adventure and spiritual town"),
 "haridwar": ("haridwar", "Haridwar", "B", "pilgrimage city"),
 "nainital": ("nainital", "Nainital", "A", "hill station"),
 "mussoorie": ("mussoorie", "Mussoorie", "A", "hill station"),
 "jim-corbett": ("jim-corbett", "Jim Corbett", "B", "national park"),
 "auli": ("auli", "Auli", "B", "ski and mountain destination"),
 "lansdowne": ("lansdowne", "Lansdowne", "B", "hill station"),
 "ranikhet": ("ranikhet", "Ranikhet", "B", "hill station"),
 "kausani": ("kausani", "Kausani", "B", "hill station"),
 "chopta": ("chopta", "Chopta", "B", "mountain meadow"),
 "kolkata": ("kolkata", "Kolkata", "A", "city"),
 "darjeeling": ("darjeeling", "Darjeeling", "A", "hill station"),
 "kalimpong": ("kalimpong", "Kalimpong", "B", "hill town"),
 "sundarbans": ("sundarbans", "Sundarbans", "B", "mangrove national park"),
 "digha": ("digha", "Digha", "B", "beach town"),
}
EXISTING = {"ranthambore-first-time-visitors": "Existing — Audited: already targets 'things to do in Ranthambore'"}
# Parent coverage for skipped guides that are parts of an eligible destination.
PARENT = [
 (r"-chandigarh$|^sector-", "chandigarh"), (r"-delhi$", "delhi"),
 (r"^(agonda|anjuna|baga|calangute|canacona|candolim|mandrem|morjim|palolem|vagator|old-goa|panjim|ponda|mollem|dudhsagar-falls)$", "goa"),
 (r"-andaman$", "andaman"), (r"^(golden-temple|wagah-border)$", "amritsar"), (r"^(charminar|golconda-fort)$", "hyderabad"),
 (r"^(ujjayanta-palace)$", "agartala"), (r"^(radhanagar-beach-andaman)$", "havelock-island"),
 (r"^(kamakhya)$", "guwahati"), (r"^(fatehpur-sikri)$", "agra"), (r"^(sarnath)$", "varanasi"),
 (r"^(abhaneri)$", "jaipur"), (r"^(khardung-la|thiksey|hemis)$", "leh"), (r"^(hunder|turtuk)$", "nubra-valley"),
 (r"^(pangong-lake|tso-moriri|lamayuru)$", "ladakh"), (r"^(tsomgo-lake|nathula-pass)$", "gangtok"),
 (r"^(nongriat|mawlynnong|dawki|laitlum-canyons|umiam-lake|krang-suri-falls)$", "meghalaya"),
 (r"^(kullu)$", "manali"), (r"^(jibhi)$", "tirthan-valley"), (r"^(khajjiar)$", "dalhousie"), (r"^(doodhpathri|yusmarg|aharbal)$", "srinagar"),
 (r"^(athirappilly|munroe-island|gavi|vagamon)$", "kerala"), (r"^(nandi-hills)$", "bangalore"), (r"^(kabini|bandipur)$", "mysore"),
 (r"^(borra-caves)$", "araku-valley"), (r"^(konark)$", "puri"), (r"^(puducherry-french-quarter)$", "pondicherry"),
 (r"^(dhanaulti)$", "mussoorie"), (r"^(mukteshwar)$", "nainital"), (r"^(govardhan)$", "mathura"),
 (r"^(elephanta|kaas-plateau)$", "pune"),
]
plan, skipped = [], []
for o in inv:
    k = o["slug"][:-len("-travel-guide")]
    if k in E:
        suf, name, tier, typ = E[k]
        plan.append({"guide": o["slug"], "slug": f"things-to-do-in-{suf}", "destination": name, "tier": tier,
                     "type": typ, "state": o["state"]})
    elif k in EXISTING:
        skipped.append({"guide": o["slug"], "reason": EXISTING[k], "action": "Existing — Audited"})
    else:
        parent = next((p for rx, p in PARENT if re.search(rx, k)), None)
        if o["hub"]:
            reason = "State/UT-level guide: things-to-do intent is served by the state's destination articles" 
        elif parent:
            reason = f"Part of a larger destination: covered in things-to-do-in-{parent}"
        elif o["words"] < 900 or o["h3"] <= 3:
            reason = "Single attraction or small place with a narrow range of activities; its guide already covers them"
        else:
            reason = "Limited standalone things-to-do search intent; activities are covered in its guide"
        skipped.append({"guide": o["slug"], "reason": reason, "action": "Skip", "parent": parent})
json.dump({"eligible": plan, "skipped": skipped}, open(os.path.join(ROOT, "scripts/things-to-do/plan.json"), "w"), indent=1)
print(len(plan), "eligible;", len(skipped), "skipped;", sum(1 for p in plan if p["tier"] == "A"), "tier A")
